import type {
  ExtractStrategy,
  GoldInsight,
  ParsedBlock,
  ParsedDocument,
} from "@/lib/schema";

export const ASSET = {
  name: "Velmara",
  molecule: "velmaratinib",
  indication: "2L EGFRm NSCLC after osimertinib",
  as_of: "2026-09-14",
};

type SeedDoc = {
  id: string;
  filename: string;
  title: string;
  stakeholder_function: ParsedDocument["stakeholder_function"];
  mime: string;
  blocks: Omit<ParsedBlock, "id">[];
};

function withIds(doc: SeedDoc): ParsedDocument {
  const blocks = doc.blocks.map((b, i) => ({
    ...b,
    id: `${doc.id}-B${String(i + 1).padStart(2, "0")}`,
  }));
  return {
    id: doc.id,
    filename: doc.filename,
    title: doc.title,
    stakeholder_function: doc.stakeholder_function,
    mime: doc.mime,
    parser: "seed",
    ingested_at: "2026-09-14T10:00:00.000Z",
    blocks,
    fullText: blocks.map((b) => `[${b.location.ref}] ${b.text}`).join("\n"),
  };
}

const commercial: SeedDoc = {
  id: "DOC-COM-001",
  filename: "Velmara_US_Brand_Plan_Q3_2026.pptx",
  title: "Velmara US Brand Plan readout — Q3 2026",
  stakeholder_function: "commercial",
  mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  blocks: [
    {
      location: { kind: "slide", ref: "Slide 1" },
      text: "Velmara US Brand Plan readout — Q3 2026",
      kind: "title",
      heading: "Title",
    },
    {
      location: { kind: "slide", ref: "Slide 2" },
      heading: "Situation",
      text: "Velmara (velmaratinib) is an oral EGFR TKI in development for 2L EGFRm NSCLC after osimertinib.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 2" },
      heading: "Situation",
      text: "PDUFA is 14 Mar 2027; US launch is assumed Q2 2027.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 3" },
      heading: "Demand",
      text: "Unrestricted access supports peak 18% share of 2L EGFRm NSCLC by year 5.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 3" },
      heading: "Demand",
      text: "Share erodes to 11% if two of the top five national accounts remain non-formulary through year 2.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 4" },
      heading: "Access risk",
      text: "Formulary decisions at Aetna and UnitedHealthcare are delayed into Q1 2027 and both accounts have requested additional 6-month discontinuation RWE.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 5" },
      heading: "Competitive",
      text: "Next-generation EGFR-MET bispecific (codename NX-441) is expected to file in 2027 and will contest the post-osimertinib setting.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 6" },
      heading: "Open questions",
      text: "Community oncology adoption versus academic centers remains unquantified. We do not have a reliable split of 2L EGFRm treated lives by site of care. Message testing of CNS differentiation has not been fielded.",
      kind: "paragraph",
    },
    {
      location: { kind: "slide", ref: "Slide 7" },
      heading: "Opportunity",
      text: "Stand up a community-focused peer-to-peer program before the first NPP to close the site-of-care evidence gap.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 8" },
      heading: "REMS",
      text: "FDA has not confirmed whether velmaratinib will require a REMS.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 9" },
      heading: "Price",
      text: "WAC is set at $18,400 per 28-day cycle and both national accounts have asked for a 340B discount policy before P&T.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 10" },
      heading: "Indication scope",
      text: "Velmara will not pursue a 1L EGFRm NSCLC indication in this planning cycle.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 11" },
      heading: "ODAC contingency",
      text: "If ODAC votes negatively, launch messaging will drop CNS differentiation claims.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 12" },
      heading: "Competitive unknown",
      text: "NX-441 filing in 2027 is expected. Peak share impact in year 3 is not modeled.",
      kind: "paragraph",
    },
    {
      location: { kind: "slide", ref: "Slide 13" },
      heading: "Share of voice",
      text: "Share of voice among community oncologists is 9% versus 31% in academic centers.",
      kind: "chart",
    },
    {
      location: { kind: "slide", ref: "Slide 13" },
      heading: "Share of voice",
      text: "Kantar Q2 2026 wave, n=142 community oncologists.",
      kind: "paragraph",
    },
    {
      location: { kind: "slide", ref: "Slide 14" },
      heading: "Samples",
      text: "Sample program start is Q1 2027 and we do not have a free-goods cap.",
      kind: "bullet",
    },
  ],
};

const marketAccess: SeedDoc = {
  id: "DOC-MA-001",
  filename: "Velmara_Payer_AdBoard_Sep2026.pptx",
  title: "Velmara payer advisory board — September 2026",
  stakeholder_function: "market_access",
  mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  blocks: [
    {
      location: { kind: "slide", ref: "Slide 1" },
      text: "Velmara payer advisory board — September 2026",
      kind: "title",
    },
    {
      location: { kind: "slide", ref: "Slide 2" },
      heading: "Objections",
      text: "ICER-style cost-effectiveness versus chemo-plus-IO is the dominant objection among national pharmacy directors.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 3" },
      heading: "Utilization management",
      text: "Payers will impose a step edit through osimertinib plus documented progression unless CNS and discontinuation data are in the AMCP dossier.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 4" },
      heading: "Medicaid",
      text: "Medicaid plans in Texas, Florida, and New York flagged high risk of preferred-product step therapy.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 5" },
      heading: "Contracting opportunity",
      text: "A regional Blues plan (Horizon) signaled openness to an outcomes-based contract tied to 6-month persistence.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 6" },
      heading: "Unknowns",
      text: "Impact of CMS IRA negotiation eligibility on net price in year 3 is not modeled.",
      kind: "paragraph",
    },
    {
      location: { kind: "slide", ref: "Slide 7" },
      heading: "Evidence gap",
      text: "No payer-ready RWE protocol exists for real-world discontinuation at 6 months.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 8" },
      heading: "Dossier requests",
      text: "National accounts want both CNS metastases subgroup data and a budget-impact model at 1% and 3% uptake.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 9" },
      heading: "Utilization operations",
      text: "Prior authorization median turnaround is 11 days in community practices versus 4 days in academic centers.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 10" },
      heading: "Copay",
      text: "Medicare Part D copay-card stacking legality remains unspecified.",
      kind: "paragraph",
    },
    {
      location: { kind: "slide", ref: "Slide 11" },
      heading: "340B",
      text: "Two IDNs (AdventHealth and CommonSpirit) requested 340B ceiling-price language in the contract.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 12" },
      heading: "Contracting limit",
      text: "Payers will not accept the Horizon outcomes-based contract as a national template.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 13" },
      heading: "Evidence gap",
      text: "Budget-impact at 5% uptake was requested but is not in the current AMCP dossier.",
      kind: "bullet",
    },
  ],
};

const medical: SeedDoc = {
  id: "DOC-MED-001",
  filename: "Velmara_KOL_Insights_Q3_2026.docx",
  title: "Medical Affairs KOL insights — Q3 2026",
  stakeholder_function: "medical_affairs",
  mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  blocks: [
    {
      location: { kind: "page", ref: "p.1" },
      heading: "Intracranial data",
      text: "KOLs consistently asked for intracranial activity data. The current clinical package has limited brain-mets representation (n=28).",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.1" },
      heading: "Sequencing",
      text: "Sequencing after osimertinib failure is the decision that will determine use; T790M is not the relevant question in 2L post-osi.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.2" },
      heading: "Testing gaps",
      text: "Community biomarker testing still misses liquid biopsy in about 30% of progressing patients in the Southeast.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.2" },
      heading: "Resistance mutations",
      text: "Some KOLs mentioned resistance mutations without specifying which alterations should trigger Velmara versus a clinical trial.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.3" },
      heading: "Medical education",
      text: "Opportunity to fund a medical education series on post-osi resistance testing.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.3" },
      heading: "Supportive data",
      text: "Unknown whether KOLs will accept tumor-agnostic EGFR exon 20 data as supportive.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.4" },
      heading: "REMS",
      text: "A REMS for velmaratinib remains unspecified, with no elements proposed.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.5" },
      heading: "Safety",
      text: "Treatment-emergent ILD occurred in 2.1% of treated patients, including one grade 5 event.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.5" },
      heading: "Safety",
      text: "QT prolongation has not been pooled across the two phase 2 cohorts.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.5" },
      heading: "Resistance mutations",
      text: "KOLs named C797S and MET amplification as possible resistance without a treatment algorithm.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.6" },
      heading: "Intracranial data",
      text: "Intracranial ORR is 38% in the n=28 brain-mets subset. KOLs called that intracranial result hypothesis-generating, not confirmatory.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.7" },
      heading: "Comparators",
      text: "No head-to-head data versus chemo-plus-IO exist in 2L EGFRm NSCLC.",
      kind: "figure",
    },
    {
      location: { kind: "page", ref: "p.8" },
      heading: "Labeling unknown",
      text: "Medical affairs cannot yet say whether interstitial lung disease will force a boxed warning in the USPI.",
      kind: "paragraph",
    },
  ],
};

const clinops: SeedDoc = {
  id: "DOC-CO-001",
  filename: "VEL-203_Enrollment_Dashboard_Sep2026.xlsx",
  title: "VEL-203 enrollment dashboard — Sep 2026",
  stakeholder_function: "clinops",
  mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  blocks: [
    {
      location: { kind: "sheet", ref: "Enrollment!B2" },
      heading: "Enrollment",
      text: "Protocol VEL-203 target 420, enrolled 281 (67%) at month 14.",
      kind: "cell",
    },
    {
      location: { kind: "sheet", ref: "Enrollment!B3" },
      heading: "Screen fail",
      text: "Screen fail rate is 41%, primary reason prior TKI washout window.",
      kind: "cell",
    },
    {
      location: { kind: "sheet", ref: "Enrollment!B4" },
      heading: "Site activation",
      text: "Southern EU site activation is 4.2 months versus 2.1 months in the US.",
      kind: "cell",
    },
    {
      location: { kind: "sheet", ref: "Enrollment!B5" },
      heading: "Protocol opportunity",
      text: "Opportunity: protocol amendment to allow concurrent biopsy during washout.",
      kind: "cell",
    },
    {
      location: { kind: "sheet", ref: "Enrollment!B6" },
      heading: "Competitive enrollment",
      text: "Unknown: impact of competing NX-441 phase 3 on remaining US sites.",
      kind: "cell",
    },
    {
      location: { kind: "sheet", ref: "Enrollment!B7" },
      heading: "Japan",
      text: "Japan first-patient-in slipped from May to September 2026.",
      kind: "cell",
    },
    {
      location: { kind: "sheet", ref: "Diversity!C2" },
      heading: "Race / ethnicity",
      text: "Hispanic / Latino enrollment is 8% versus 18% US EGFRm incidence.",
      kind: "table_cell",
    },
    {
      location: { kind: "sheet", ref: "ScreenFail!C3" },
      heading: "Screen fail mix",
      text: "Untreated brain metastases account for 14% of screen fails.",
      kind: "table_cell",
    },
    {
      location: { kind: "sheet", ref: "ExUS!B2" },
      heading: "China",
      text: "China CTA approval has not been filed.",
      kind: "cell",
    },
    {
      location: { kind: "sheet", ref: "Sites!B4" },
      heading: "Site strategy",
      text: "Opportunity: open two additional community sites in Florida to offset NX-441 competition.",
      kind: "cell",
    },
  ],
};

const marketing: SeedDoc = {
  id: "DOC-MKT-001",
  filename: "Velmara_Unbranded_Campaign_Readout_Q3.pptx",
  title: "Velmara unbranded campaign readout — Q3 2026",
  stakeholder_function: "marketing",
  mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  blocks: [
    {
      location: { kind: "slide", ref: "Slide 1" },
      text: "Velmara unbranded campaign readout — Q3 2026",
      kind: "title",
    },
    {
      location: { kind: "slide", ref: "Slide 2" },
      heading: "Channel mix",
      text: "Unbranded disease-awareness impressions over-index 3.2x in academic versus community settings.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 3" },
      heading: "Message recall",
      text: "Message recall is 64% for once-daily oral and 19% for CNS coverage.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 4" },
      heading: "Patient support",
      text: "Patient support program NPS is not measured.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 5" },
      heading: "Email",
      text: "HCP email open rate is 28% versus a 22% benchmark.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 6" },
      heading: "Media opportunity",
      text: "Opportunity: shift 40% of unbranded spend to community oncology networks in Texas, Florida, and Ohio.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 7" },
      heading: "Message unknown",
      text: "Unknown whether the post-osi sequencing message is differentiated versus competitor unbranded campaigns.",
      kind: "paragraph",
    },
    {
      location: { kind: "slide", ref: "Slide 8" },
      heading: "Advocacy",
      text: "Patient advocacy asked for ILD counseling materials before any branded launch.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 9" },
      heading: "DTC",
      text: "DTC spend is paused until FDA confirms whether a REMS is required.",
      kind: "bullet",
    },
    {
      location: { kind: "slide", ref: "Slide 10" },
      heading: "Awareness",
      text: "Unaided awareness of post-osi options is 22% in community versus 61% academic.",
      kind: "chart",
    },
    {
      location: { kind: "slide", ref: "Slide 11" },
      heading: "Speaker bureau",
      text: "Speaker bureau contract with Dr. Hale was declined. No replacement KOL is booked for Q4.",
      kind: "paragraph",
    },
  ],
};

const heor: SeedDoc = {
  id: "DOC-HEOR-001",
  filename: "Velmara_HEOR_ICER_Pack_Sep2026.xlsx",
  title: "Velmara HEOR ICER pack — Sep 2026",
  stakeholder_function: "heor",
  mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  blocks: [
    {
      location: { kind: "sheet", ref: "ICER!C2" },
      heading: "Base case",
      text: "Base-case ICER versus chemo-plus-IO is $247,000 per QALY.",
      kind: "table_cell",
    },
    {
      location: { kind: "sheet", ref: "ICER!C3" },
      heading: "Threshold",
      text: "ICER exceeds the $150,000 per QALY threshold used by national pharmacy directors.",
      kind: "table_cell",
    },
    {
      location: { kind: "sheet", ref: "PSA!C2" },
      heading: "PSA",
      text: "Probabilistic sensitivity analysis puts the probability of cost-effectiveness at 18% at $150,000/QALY.",
      kind: "table_cell",
    },
    {
      location: { kind: "sheet", ref: "BIM!C2" },
      heading: "Budget impact 1%",
      text: "Budget impact at 1% uptake is $42 million.",
      kind: "table_cell",
    },
    {
      location: { kind: "sheet", ref: "BIM!C3" },
      heading: "Budget impact 3%",
      text: "Budget impact at 3% uptake is $119 million.",
      kind: "table_cell",
    },
    {
      location: { kind: "sheet", ref: "BIM!C4" },
      heading: "Caregiver",
      text: "Caregiver productivity offsets are not modeled.",
      kind: "cell",
    },
    {
      location: { kind: "sheet", ref: "Inputs!B2" },
      heading: "List price",
      text: "WAC of $18,400 per cycle is the HEOR list-price assumption.",
      kind: "cell",
    },
    {
      location: { kind: "sheet", ref: "Plan!B3" },
      heading: "Engagement",
      text: "Opportunity: convene an ICER engagement before the AMCP dossier lock in November 2026.",
      kind: "cell",
    },
    {
      location: { kind: "sheet", ref: "IRA!B2" },
      heading: "IRA unknown",
      text: "Unknown whether CMS IRA negotiation in year 3 would rebase the ICER below threshold.",
      kind: "cell",
    },
  ],
};

const regulatory: SeedDoc = {
  id: "DOC-REG-001",
  filename: "Velmara_FDA_Interaction_Log_Q3_2026.docx",
  title: "Velmara FDA interaction log — Q3 2026",
  stakeholder_function: "regulatory",
  mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  blocks: [
    {
      location: { kind: "page", ref: "p.1" },
      heading: "PDUFA clock",
      text: "The PDUFA clock is paused 21 days pending a late CMC information request.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.1" },
      heading: "Safety labeling",
      text: "FDA has not confirmed a boxed warning for ILD.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.2" },
      heading: "CMC",
      text: "The 12-month primary stability package is incomplete for two process-validation lots.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.2" },
      heading: "PREA",
      text: "PREA pediatric deferral has been requested; FDA response is outstanding.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.3" },
      heading: "Advisory committee",
      text: "An ODAC date has not been scheduled.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.3" },
      heading: "Labeling",
      text: "FDA asked whether the n=28 intracranial subset will appear in section 14 of labeling.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.4" },
      heading: "REMS",
      text: "A REMS with ETASU has not been proposed by the sponsor.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.4" },
      heading: "Meeting opportunity",
      text: "Opportunity: request a Type B meeting on the CNS subgroup before label negotiations.",
      kind: "paragraph",
    },
    {
      location: { kind: "page", ref: "p.5" },
      heading: "Supportive data",
      text: "Unknown whether FDA will allow tumor-agnostic EGFR exon 20 data in the clinical studies section.",
      kind: "paragraph",
    },
  ],
};

export const SEED_DOCUMENTS: ParsedDocument[] = [
  commercial,
  marketAccess,
  medical,
  clinops,
  marketing,
  heor,
  regulatory,
].map(withIds);

export const THEME_CATALOG = [
  {
    id: "THEME-ACCESS",
    name: "Access & formulary",
    summary:
      "National and Medicaid coverage, step edits, and the RWE the accounts are using to delay decisions.",
    keywords: [
      "formulary",
      "aetna",
      "unitedhealthcare",
      "medicaid",
      "step",
      "amcp",
      "account",
      "access",
      "horizon",
      "contract",
      "payer",
      "340b",
      "copay",
      "prior auth",
      "wac",
    ],
  },
  {
    id: "THEME-EVIDENCE",
    summary:
      "CNS, discontinuation, intracranial, and payer-ready RWE packages that multiple functions say are missing.",
    name: "Evidence gaps",
    keywords: [
      "rwe",
      "cns",
      "discontinuation",
      "intracranial",
      "brain",
      "dossier",
      "n=28",
      "persistence",
      "evidence",
      "interstitial",
      "orr",
      "head-to-head",
      "labeling",
    ],
  },
  {
    id: "THEME-COMPETITIVE",
    name: "Competitive dynamics",
    summary: "NX-441 and other post-osi threats to share, sites, and messaging.",
    keywords: ["nx-441", "bispecific", "competitor", "competitive", "file"],
  },
  {
    id: "THEME-SITE-OF-CARE",
    name: "Community vs academic",
    summary:
      "Where 2L lives are treated, whether community adopts, and whether spend and testing follow.",
    keywords: [
      "community",
      "academic",
      "site of care",
      "peer-to-peer",
      "southeast",
      "prior auth",
    ],
  },
  {
    id: "THEME-TRIAL",
    name: "Trial execution",
    summary: "VEL-203 enrollment, screen fail, activation lag, and protocol design.",
    keywords: [
      "enrolled",
      "screen fail",
      "washout",
      "site activation",
      "japan",
      "vel-203",
      "protocol",
      "biopsy",
      "hispanic",
      "diversity",
    ],
  },
  {
    id: "THEME-HCP",
    name: "HCP engagement & messaging",
    summary: "Recall, channel mix, NPS, and whether sequencing copy is differentiated.",
    keywords: [
      "message",
      "recall",
      "nps",
      "email",
      "unbranded",
      "impressions",
      "spend",
      "share of voice",
      "dtc",
      "awareness",
      "speaker",
    ],
  },
  {
    id: "THEME-SEQUENCING",
    name: "Sequencing & resistance",
    summary:
      "Post-osi use, T790M irrelevance, and unspecified resistance mutations KOLs keep raising.",
    keywords: [
      "sequencing",
      "t790m",
      "resistance",
      "post-osi",
      "exon",
      "liquid biopsy",
      "c797s",
      "met amp",
    ],
  },
  {
    id: "THEME-POLICY",
    name: "Pricing & policy",
    summary: "IRA negotiation, net price, ICER-style objections, and budget impact.",
    keywords: [
      "ira",
      "cms",
      "icer",
      "net price",
      "budget-impact",
      "uptake",
      "wac",
      "qaly",
      "340b",
    ],
  },
  {
    id: "THEME-RESIDUAL",
    name: "Unassigned",
    summary:
      "Insights that did not clear the catalog threshold. Held once, never copied, and queued for a new theme proposal rather than forced into a blob.",
    keywords: [],
  },
];

export const GOLD_INSIGHTS: GoldInsight[] = [
  {
    id: "GOLD-001",
    statement:
      "Velmara (velmaratinib) is an oral EGFR TKI in development for 2L EGFRm NSCLC after osimertinib.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-SEQUENCING"],
    must_find: true,
  },
  {
    id: "GOLD-002",
    statement: "PDUFA is 14 Mar 2027; US launch is assumed Q2 2027.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-003",
    statement:
      "Unrestricted access supports peak 18% share of 2L EGFRm NSCLC by year 5.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-004",
    statement:
      "Share erodes to 11% if two of the top five national accounts remain non-formulary through year 2.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-005",
    statement:
      "Formulary decisions at Aetna and UnitedHealthcare are delayed into Q1 2027.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-006",
    statement:
      "Aetna and UnitedHealthcare have requested additional 6-month discontinuation RWE.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-EVIDENCE", "THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-007",
    statement:
      "Next-generation EGFR-MET bispecific NX-441 is expected to file in 2027 and will contest the post-osimertinib setting.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-COMPETITIVE"],
    must_find: true,
  },
  {
    id: "GOLD-008",
    statement:
      "Community oncology adoption versus academic centers remains unquantified.",
    source_document_id: "DOC-COM-001",
    classification: "unknown",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-SITE-OF-CARE"],
    must_find: true,
  },
  {
    id: "GOLD-009",
    statement:
      "There is no reliable split of 2L EGFRm treated lives by site of care.",
    source_document_id: "DOC-COM-001",
    classification: "unknown",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-SITE-OF-CARE"],
    must_find: true,
  },
  {
    id: "GOLD-010",
    statement: "Message testing of CNS differentiation has not been fielded.",
    source_document_id: "DOC-COM-001",
    classification: "unknown",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-HCP", "THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-011",
    statement:
      "Stand up a community-focused peer-to-peer program before the first NPP to close the site-of-care evidence gap.",
    source_document_id: "DOC-COM-001",
    classification: "opportunity",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-SITE-OF-CARE"],
    must_find: true,
  },
  {
    id: "GOLD-012",
    statement:
      "ICER-style cost-effectiveness versus chemo-plus-IO is the dominant objection among national pharmacy directors.",
    source_document_id: "DOC-MA-001",
    classification: "known",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-013",
    statement:
      "Payers will impose a step edit through osimertinib plus documented progression unless CNS and discontinuation data are in the AMCP dossier.",
    source_document_id: "DOC-MA-001",
    classification: "known",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-ACCESS", "THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-014",
    statement:
      "Medicaid plans in Texas, Florida, and New York flagged high risk of preferred-product step therapy.",
    source_document_id: "DOC-MA-001",
    classification: "known",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-015",
    statement:
      "Horizon signaled openness to an outcomes-based contract tied to 6-month persistence.",
    source_document_id: "DOC-MA-001",
    classification: "opportunity",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-016",
    statement:
      "Impact of CMS IRA negotiation eligibility on net price in year 3 is not modeled.",
    source_document_id: "DOC-MA-001",
    classification: "unknown",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-017",
    statement:
      "No payer-ready RWE protocol exists for real-world discontinuation at 6 months.",
    source_document_id: "DOC-MA-001",
    classification: "unknown",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-EVIDENCE", "THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-018",
    statement: "National accounts want CNS metastases subgroup data.",
    source_document_id: "DOC-MA-001",
    classification: "known",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-EVIDENCE", "THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-019",
    statement:
      "National accounts want a budget-impact model at 1% and 3% uptake.",
    source_document_id: "DOC-MA-001",
    classification: "known",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-POLICY", "THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-020",
    statement: "KOLs consistently asked for intracranial activity data.",
    source_document_id: "DOC-MED-001",
    classification: "known",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-021",
    statement:
      "The current clinical package has limited brain-mets representation (n=28).",
    source_document_id: "DOC-MED-001",
    classification: "known",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-022",
    statement:
      "Sequencing after osimertinib failure is the decision that will determine use.",
    source_document_id: "DOC-MED-001",
    classification: "known",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-SEQUENCING"],
    must_find: true,
  },
  {
    id: "GOLD-023",
    statement: "T790M is not the relevant question in 2L post-osi.",
    source_document_id: "DOC-MED-001",
    classification: "known",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-SEQUENCING"],
    must_find: true,
  },
  {
    id: "GOLD-024",
    statement:
      "Community biomarker testing still misses liquid biopsy in about 30% of progressing patients in the Southeast.",
    source_document_id: "DOC-MED-001",
    classification: "known",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-SITE-OF-CARE", "THEME-SEQUENCING"],
    must_find: true,
  },
  {
    id: "GOLD-025",
    statement:
      "Some KOLs mentioned resistance mutations without specifying which alterations should trigger Velmara versus a clinical trial.",
    source_document_id: "DOC-MED-001",
    classification: "unknown",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-SEQUENCING"],
    must_find: true,
  },
  {
    id: "GOLD-026",
    statement:
      "Opportunity to fund a medical education series on post-osi resistance testing.",
    source_document_id: "DOC-MED-001",
    classification: "opportunity",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-SEQUENCING"],
    must_find: true,
  },
  {
    id: "GOLD-027",
    statement:
      "Unknown whether KOLs will accept tumor-agnostic EGFR exon 20 data as supportive.",
    source_document_id: "DOC-MED-001",
    classification: "unknown",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-028",
    statement: "Protocol VEL-203 is at 281 enrolled of 420 target (67%) at month 14.",
    source_document_id: "DOC-CO-001",
    classification: "known",
    stakeholder_function: "clinops",
    theme_ids: ["THEME-TRIAL"],
    must_find: true,
  },
  {
    id: "GOLD-029",
    statement:
      "Screen fail rate is 41%, primary reason prior TKI washout window.",
    source_document_id: "DOC-CO-001",
    classification: "known",
    stakeholder_function: "clinops",
    theme_ids: ["THEME-TRIAL"],
    must_find: true,
  },
  {
    id: "GOLD-030",
    statement:
      "Southern EU site activation is 4.2 months versus 2.1 months in the US.",
    source_document_id: "DOC-CO-001",
    classification: "known",
    stakeholder_function: "clinops",
    theme_ids: ["THEME-TRIAL"],
    must_find: true,
  },
  {
    id: "GOLD-031",
    statement:
      "Protocol amendment to allow concurrent biopsy during washout.",
    source_document_id: "DOC-CO-001",
    classification: "opportunity",
    stakeholder_function: "clinops",
    theme_ids: ["THEME-TRIAL"],
    must_find: true,
  },
  {
    id: "GOLD-032",
    statement:
      "Impact of competing NX-441 phase 3 on remaining US sites is unknown.",
    source_document_id: "DOC-CO-001",
    classification: "unknown",
    stakeholder_function: "clinops",
    theme_ids: ["THEME-COMPETITIVE", "THEME-TRIAL"],
    must_find: true,
  },
  {
    id: "GOLD-033",
    statement: "Japan first-patient-in slipped from May to September 2026.",
    source_document_id: "DOC-CO-001",
    classification: "known",
    stakeholder_function: "clinops",
    theme_ids: ["THEME-TRIAL"],
    must_find: true,
  },
  {
    id: "GOLD-034",
    statement:
      "Unbranded disease-awareness impressions over-index 3.2x in academic versus community settings.",
    source_document_id: "DOC-MKT-001",
    classification: "known",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-HCP"],
    must_find: true,
  },
  {
    id: "GOLD-035",
    statement:
      "Message recall is 64% for once-daily oral and 19% for CNS coverage.",
    source_document_id: "DOC-MKT-001",
    classification: "known",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-HCP"],
    must_find: true,
  },
  {
    id: "GOLD-036",
    statement: "Patient support program NPS is not measured.",
    source_document_id: "DOC-MKT-001",
    classification: "unknown",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-HCP"],
    must_find: true,
  },
  {
    id: "GOLD-037",
    statement: "HCP email open rate is 28% versus a 22% benchmark.",
    source_document_id: "DOC-MKT-001",
    classification: "known",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-HCP"],
    must_find: false,
  },
  {
    id: "GOLD-038",
    statement:
      "Shift 40% of unbranded spend to community oncology networks in Texas, Florida, and Ohio.",
    source_document_id: "DOC-MKT-001",
    classification: "opportunity",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-SITE-OF-CARE", "THEME-HCP"],
    must_find: true,
  },
  {
    id: "GOLD-039",
    statement:
      "Unknown whether the post-osi sequencing message is differentiated versus competitor unbranded campaigns.",
    source_document_id: "DOC-MKT-001",
    classification: "unknown",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-HCP", "THEME-SEQUENCING", "THEME-COMPETITIVE"],
    must_find: true,
  },
  {
    id: "GOLD-040",
    statement:
      "FDA has not confirmed whether velmaratinib will require a REMS.",
    source_document_id: "DOC-COM-001",
    classification: "unknown",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-RESIDUAL"],
    must_find: false,
  },
  {
    id: "GOLD-041",
    statement:
      "A REMS for velmaratinib remains unspecified, with no elements proposed.",
    source_document_id: "DOC-MED-001",
    classification: "unknown",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-RESIDUAL"],
    must_find: false,
  },
  {
    id: "GOLD-042",
    statement: "WAC is set at $18,400 per 28-day cycle.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-POLICY", "THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-043",
    statement:
      "Both national accounts have asked for a 340B discount policy before P&T.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-ACCESS", "THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-044",
    statement:
      "Velmara will not pursue a 1L EGFRm NSCLC indication in this planning cycle.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-SEQUENCING"],
    must_find: true,
  },
  {
    id: "GOLD-045",
    statement:
      "If ODAC votes negatively, launch messaging will drop CNS differentiation claims.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-HCP", "THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-046",
    statement: "Peak share impact in year 3 is not modeled.",
    source_document_id: "DOC-COM-001",
    classification: "unknown",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-COMPETITIVE", "THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-047",
    statement:
      "Share of voice among community oncologists is 9% versus 31% in academic centers.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-HCP", "THEME-SITE-OF-CARE"],
    must_find: true,
  },
  {
    id: "GOLD-048",
    statement: "Kantar Q2 2026 wave, n=142 community oncologists.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-HCP"],
    must_find: false,
  },
  {
    id: "GOLD-049",
    statement: "Sample program start is Q1 2027.",
    source_document_id: "DOC-COM-001",
    classification: "known",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-050",
    statement: "We do not have a free-goods cap.",
    source_document_id: "DOC-COM-001",
    classification: "unknown",
    stakeholder_function: "commercial",
    theme_ids: ["THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-051",
    statement:
      "Prior authorization median turnaround is 11 days in community practices versus 4 days in academic centers.",
    source_document_id: "DOC-MA-001",
    classification: "known",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-ACCESS", "THEME-SITE-OF-CARE"],
    must_find: true,
  },
  {
    id: "GOLD-052",
    statement:
      "Medicare Part D copay-card stacking legality remains unspecified.",
    source_document_id: "DOC-MA-001",
    classification: "unknown",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-ACCESS", "THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-053",
    statement:
      "Two IDNs (AdventHealth and CommonSpirit) requested 340B ceiling-price language in the contract.",
    source_document_id: "DOC-MA-001",
    classification: "known",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-ACCESS", "THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-054",
    statement:
      "Payers will not accept the Horizon outcomes-based contract as a national template.",
    source_document_id: "DOC-MA-001",
    classification: "known",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-055",
    statement:
      "Budget-impact at 5% uptake was requested but is not in the current AMCP dossier.",
    source_document_id: "DOC-MA-001",
    classification: "unknown",
    stakeholder_function: "market_access",
    theme_ids: ["THEME-POLICY", "THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-056",
    statement:
      "Treatment-emergent ILD occurred in 2.1% of treated patients, including one grade 5 event.",
    source_document_id: "DOC-MED-001",
    classification: "known",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-057",
    statement:
      "QT prolongation has not been pooled across the two phase 2 cohorts.",
    source_document_id: "DOC-MED-001",
    classification: "unknown",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-058",
    statement:
      "KOLs named C797S and MET amplification as possible resistance without a treatment algorithm.",
    source_document_id: "DOC-MED-001",
    classification: "unknown",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-SEQUENCING"],
    must_find: true,
  },
  {
    id: "GOLD-059",
    statement:
      "Intracranial ORR is 38% in the n=28 brain-mets subset.",
    source_document_id: "DOC-MED-001",
    classification: "known",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-060",
    statement:
      "KOLs called that intracranial result hypothesis-generating, not confirmatory.",
    source_document_id: "DOC-MED-001",
    classification: "known",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-061",
    statement:
      "No head-to-head data versus chemo-plus-IO exist in 2L EGFRm NSCLC.",
    source_document_id: "DOC-MED-001",
    classification: "unknown",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-EVIDENCE", "THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-062",
    statement:
      "Medical affairs cannot yet say whether interstitial lung disease will force a boxed warning in the USPI.",
    source_document_id: "DOC-MED-001",
    classification: "unknown",
    stakeholder_function: "medical_affairs",
    theme_ids: ["THEME-RESIDUAL"],
    must_find: true,
  },
  {
    id: "GOLD-063",
    statement:
      "Hispanic / Latino enrollment is 8% versus 18% US EGFRm incidence.",
    source_document_id: "DOC-CO-001",
    classification: "known",
    stakeholder_function: "clinops",
    theme_ids: ["THEME-TRIAL", "THEME-SITE-OF-CARE"],
    must_find: true,
  },
  {
    id: "GOLD-064",
    statement:
      "Untreated brain metastases account for 14% of screen fails.",
    source_document_id: "DOC-CO-001",
    classification: "known",
    stakeholder_function: "clinops",
    theme_ids: ["THEME-TRIAL", "THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-065",
    statement: "China CTA approval has not been filed.",
    source_document_id: "DOC-CO-001",
    classification: "unknown",
    stakeholder_function: "clinops",
    theme_ids: ["THEME-TRIAL"],
    must_find: false,
  },
  {
    id: "GOLD-066",
    statement:
      "Open two additional community sites in Florida to offset NX-441 competition.",
    source_document_id: "DOC-CO-001",
    classification: "opportunity",
    stakeholder_function: "clinops",
    theme_ids: ["THEME-TRIAL", "THEME-COMPETITIVE", "THEME-SITE-OF-CARE"],
    must_find: true,
  },
  {
    id: "GOLD-067",
    statement:
      "Patient advocacy asked for ILD counseling materials before any branded launch.",
    source_document_id: "DOC-MKT-001",
    classification: "known",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-HCP"],
    must_find: true,
  },
  {
    id: "GOLD-068",
    statement:
      "DTC spend is paused until FDA confirms whether a REMS is required.",
    source_document_id: "DOC-MKT-001",
    classification: "unknown",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-HCP"],
    must_find: true,
  },
  {
    id: "GOLD-069",
    statement:
      "Unaided awareness of post-osi options is 22% in community versus 61% academic.",
    source_document_id: "DOC-MKT-001",
    classification: "known",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-HCP", "THEME-SITE-OF-CARE"],
    must_find: true,
  },
  {
    id: "GOLD-070",
    statement: "Speaker bureau contract with Dr. Hale was declined.",
    source_document_id: "DOC-MKT-001",
    classification: "known",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-HCP"],
    must_find: false,
  },
  {
    id: "GOLD-071",
    statement: "No replacement KOL is booked for Q4.",
    source_document_id: "DOC-MKT-001",
    classification: "known",
    stakeholder_function: "marketing",
    theme_ids: ["THEME-HCP"],
    must_find: false,
  },
  {
    id: "GOLD-072",
    statement:
      "Base-case ICER versus chemo-plus-IO is $247,000 per QALY.",
    source_document_id: "DOC-HEOR-001",
    classification: "known",
    stakeholder_function: "heor",
    theme_ids: ["THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-073",
    statement:
      "ICER exceeds the $150,000 per QALY threshold used by national pharmacy directors.",
    source_document_id: "DOC-HEOR-001",
    classification: "known",
    stakeholder_function: "heor",
    theme_ids: ["THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-074",
    statement:
      "Probabilistic sensitivity analysis puts the probability of cost-effectiveness at 18% at $150,000/QALY.",
    source_document_id: "DOC-HEOR-001",
    classification: "known",
    stakeholder_function: "heor",
    theme_ids: ["THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-075",
    statement: "Budget impact at 1% uptake is $42 million.",
    source_document_id: "DOC-HEOR-001",
    classification: "known",
    stakeholder_function: "heor",
    theme_ids: ["THEME-POLICY", "THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-076",
    statement: "Budget impact at 3% uptake is $119 million.",
    source_document_id: "DOC-HEOR-001",
    classification: "known",
    stakeholder_function: "heor",
    theme_ids: ["THEME-POLICY", "THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-077",
    statement: "Caregiver productivity offsets are not modeled.",
    source_document_id: "DOC-HEOR-001",
    classification: "unknown",
    stakeholder_function: "heor",
    theme_ids: ["THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-078",
    statement:
      "WAC of $18,400 per cycle is the HEOR list-price assumption.",
    source_document_id: "DOC-HEOR-001",
    classification: "known",
    stakeholder_function: "heor",
    theme_ids: ["THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-079",
    statement:
      "Convene an ICER engagement before the AMCP dossier lock in November 2026.",
    source_document_id: "DOC-HEOR-001",
    classification: "opportunity",
    stakeholder_function: "heor",
    theme_ids: ["THEME-POLICY", "THEME-ACCESS"],
    must_find: true,
  },
  {
    id: "GOLD-080",
    statement:
      "Unknown whether CMS IRA negotiation in year 3 would rebase the ICER below threshold.",
    source_document_id: "DOC-HEOR-001",
    classification: "unknown",
    stakeholder_function: "heor",
    theme_ids: ["THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-081",
    statement:
      "The PDUFA clock is paused 21 days pending a late CMC information request.",
    source_document_id: "DOC-REG-001",
    classification: "known",
    stakeholder_function: "regulatory",
    theme_ids: ["THEME-POLICY"],
    must_find: true,
  },
  {
    id: "GOLD-082",
    statement: "FDA has not confirmed a boxed warning for ILD.",
    source_document_id: "DOC-REG-001",
    classification: "unknown",
    stakeholder_function: "regulatory",
    theme_ids: ["THEME-RESIDUAL"],
    must_find: true,
  },
  {
    id: "GOLD-083",
    statement:
      "The 12-month primary stability package is incomplete for two process-validation lots.",
    source_document_id: "DOC-REG-001",
    classification: "known",
    stakeholder_function: "regulatory",
    theme_ids: ["THEME-RESIDUAL"],
    must_find: true,
  },
  {
    id: "GOLD-084",
    statement: "PREA pediatric deferral has been requested.",
    source_document_id: "DOC-REG-001",
    classification: "known",
    stakeholder_function: "regulatory",
    theme_ids: ["THEME-RESIDUAL"],
    must_find: false,
  },
  {
    id: "GOLD-085",
    statement: "FDA response is outstanding.",
    source_document_id: "DOC-REG-001",
    classification: "unknown",
    stakeholder_function: "regulatory",
    theme_ids: ["THEME-RESIDUAL"],
    must_find: false,
  },
  {
    id: "GOLD-086",
    statement: "An ODAC date has not been scheduled.",
    source_document_id: "DOC-REG-001",
    classification: "unknown",
    stakeholder_function: "regulatory",
    theme_ids: ["THEME-RESIDUAL"],
    must_find: true,
  },
  {
    id: "GOLD-087",
    statement:
      "FDA asked whether the n=28 intracranial subset will appear in section 14 of labeling.",
    source_document_id: "DOC-REG-001",
    classification: "unknown",
    stakeholder_function: "regulatory",
    theme_ids: ["THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-088",
    statement: "A REMS with ETASU has not been proposed by the sponsor.",
    source_document_id: "DOC-REG-001",
    classification: "unknown",
    stakeholder_function: "regulatory",
    theme_ids: ["THEME-RESIDUAL"],
    must_find: false,
  },
  {
    id: "GOLD-089",
    statement:
      "Request a Type B meeting on the CNS subgroup before label negotiations.",
    source_document_id: "DOC-REG-001",
    classification: "opportunity",
    stakeholder_function: "regulatory",
    theme_ids: ["THEME-EVIDENCE"],
    must_find: true,
  },
  {
    id: "GOLD-090",
    statement:
      "Unknown whether FDA will allow tumor-agnostic EGFR exon 20 data in the clinical studies section.",
    source_document_id: "DOC-REG-001",
    classification: "unknown",
    stakeholder_function: "regulatory",
    theme_ids: ["THEME-EVIDENCE", "THEME-SEQUENCING"],
    must_find: true,
  },
];

export const STRATEGY_BY_VERSION: Record<string, ExtractStrategy> = {
  "v1.0-baseline": "bullet-only",
  "v1.1-atomic": "claim-split",
  "v1.2-gap-sensitive": "gap-scan",
  "v1.3-cross-functional": "full",
};
