import type { IegpState } from "./types";

const AT = "2026-09-17T00:00:00.000Z";

/** Empty IEGP: Velmara asset + objectives only. No sources, gaps, or tactics. */
export function buildBlankWorkspace(): IegpState {
  return {
    asset: {
      id: "ASSET-VELMARA",
      name: "Velmara",
      inn: "velmaratinib",
      indication: "2L EGFR-mutant NSCLC",
      geography: "US + EU5",
      wizard_complete: false,
    },
    objectives: [
      {
        id: "OBJ-REIMB",
        name: "Support reimbursement and HTA",
        description: "Generate decision-grade evidence for US payers and EU5 HTA.",
        lifecycle_stage: "peri-launch",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US + EU5",
        strategic_importance: 5,
        key_decision: "US national payer P&T and EU5 HTA filings",
        decision_date: "2027-03-31",
        owner: "T. Okonkwo",
      },
      {
        id: "OBJ-DIFF",
        name: "Demonstrate differentiated clinical value",
        description: "Position Velmara versus osimertinib and NX-441.",
        lifecycle_stage: "peri-launch",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US + EU5",
        strategic_importance: 5,
        key_decision: "Brand strategy lock",
        decision_date: "2026-12-15",
        owner: "M. Hale",
      },
      {
        id: "OBJ-ELDERLY",
        name: "Establish value in elderly and frail patients",
        description: "Answer the elderly SoC question that HTA and KOLs keep raising.",
        lifecycle_stage: "peri-launch",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US + EU5",
        strategic_importance: 5,
        key_decision: "HTA elderly subgroup package",
        decision_date: "2027-01-15",
        owner: "A. Rao",
      },
      {
        id: "OBJ-BURDEN",
        name: "Characterise burden of CNS disease and recurrence",
        description: "Clinical, HCRU and economic burden to feed models and medical.",
        lifecycle_stage: "peri-launch",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US + EU5",
        strategic_importance: 4,
        key_decision: "CEA/BIM input freeze",
        decision_date: "2026-11-30",
        owner: "A. Rao",
      },
      {
        id: "OBJ-SEQ",
        name: "Support treatment sequencing",
        description: "Where Velmara sits after osimertinib and versus NX-441.",
        lifecycle_stage: "lifecycle",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US + EU5",
        strategic_importance: 4,
        key_decision: "Medical sequencing narrative",
        decision_date: "2027-06-01",
        owner: "M. Hale",
      },
      {
        id: "OBJ-ACCESS",
        name: "Improve patient access",
        description: "Formulary, IRA net price, persistence RWE.",
        lifecycle_stage: "peri-launch",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US",
        strategic_importance: 5,
        key_decision: "Aetna / UHC formulary",
        decision_date: "2026-12-01",
        owner: "T. Okonkwo",
      },
    ],
    sources: [],
    blocks: [],
    needs: [],
    gaps: [],
    need_gap_links: [],
    tactics: [],
    coverages: [],
    mapping_suggestions: [],
    residual_gap_suggestions: [],
    residuals: [],
    priorities: [],
    roadmap: [],
    audit: [
      {
        id: "AUD-BLANK",
        at: AT,
        actor_name: "System",
        actor_function: "evidence_lead",
        entity_type: "plan",
        entity_id: "ASSET-VELMARA",
        action: "blank",
        detail:
          "Blank IEGP workspace. Sidebar places: upload → review → mappings → library → plan. Demo files wait on Upload until a human ingest them.",
      },
    ],
    gold_needs: [],
    gold_coverages: [],
  };
}
