import { unlocked, emptyDimensions } from "./engine";
import type {
  ActorFunction,
  CoverageDimension,
  DimensionValue,
  OverallCoverage,
} from "./enums";
import type {
  DimensionAssessment,
  IegpState,
  Lock,
  SourceBlock,
} from "./types";

const AT = "2026-09-10T12:00:00.000Z";

function lock(
  name: string,
  fn: ActorFunction,
  note?: string,
  at = AT,
): Lock {
  return {
    locked: true,
    actor_name: name,
    actor_function: fn,
    locked_at: at,
    note: note ?? null,
  };
}

function dims(
  values: Partial<Record<CoverageDimension, DimensionValue>>,
  rationale: string,
  who: [string, ActorFunction],
): Record<CoverageDimension, DimensionAssessment> {
  const base = emptyDimensions();
  for (const [k, v] of Object.entries(values) as [CoverageDimension, DimensionValue][]) {
    base[k] = {
      value: v,
      rationale,
      lock: lock(who[0], who[1], rationale),
    };
  }
  return base;
}

function coverage(args: {
  id: string;
  gap_id: string;
  tactic_id: string;
  overall: OverallCoverage;
  rationale: string;
  values: Partial<Record<CoverageDimension, DimensionValue>>;
  who: [string, ActorFunction];
  stale?: boolean;
}) {
  return {
    id: args.id,
    gap_id: args.gap_id,
    tactic_id: args.tactic_id,
    dimensions: dims(args.values, args.rationale, args.who),
    overall: args.overall,
    overall_rationale: args.rationale,
    overall_lock: lock(args.who[0], args.who[1], args.rationale),
    stale: args.stale ?? false,
    needs_review: false,
  };
}

function blocks(
  source_id: string,
  rows: { heading: string; text: string; location: string }[],
): SourceBlock[] {
  return rows.map((r, i) => ({
    id: `${source_id}-B${String(i + 1).padStart(2, "0")}`,
    source_id,
    ...r,
  }));
}

export function buildSeed(): IegpState {
  const rao: [string, ActorFunction] = ["A. Rao", "heor"];
  const hale: [string, ActorFunction] = ["M. Hale", "medical_affairs"];
  const chen: [string, ActorFunction] = ["L. Chen", "rwe"];
  const okonkwo: [string, ActorFunction] = ["T. Okonkwo", "market_access"];
  const lead: [string, ActorFunction] = ["S. Iyer", "evidence_lead"];

  const srcBlocks: SourceBlock[] = [
    ...blocks("SRC-INT-HEOR", [
      {
        heading: "Burden",
        location: "Interview note 1",
        text: "We need to understand the economic burden associated with recurrence after velmaratinib. Limited evidence characterises direct costs of repeat procedures in routine practice.",
      },
      {
        heading: "Elderly",
        location: "Interview note 2",
        text: "HTA colleagues keep asking whether we have comparative effectiveness of Velmara versus regional standard of care in elderly patients. We don't have enough evidence in patients aged 65 and over.",
      },
    ]),
    ...blocks("SRC-INT-MED", [
      {
        heading: "CNS",
        location: "KOL interview",
        text: "KOLs need to know intracranial outcomes. Limited evidence on CNS response and duration in patients with brain metastases remains an open question for medical affairs.",
      },
      {
        heading: "Sequencing",
        location: "Advisory debrief",
        text: "We need to characterise real-world treatment sequencing after osimertinib failure. Insufficient data on where Velmara sits versus NX-441.",
      },
    ]),
    ...blocks("SRC-INT-ACCESS", [
      {
        heading: "Payer RWE",
        location: "Ad board",
        text: "Aetna and UnitedHealthcare need to understand 6-month discontinuation in routine care. Limited evidence on persistence is blocking formulary.",
      },
      {
        heading: "IRA",
        location: "Access interview",
        text: "We need to quantify IRA net-price exposure for Velmara. Unknown whether the current BIM reflects the negotiated-price scenario.",
      },
    ]),
    ...blocks("SRC-TLR-001", [
      {
        heading: "HCRU after recurrence",
        location: "Study A",
        text: "Study A reports hospitalisations after EGFR TKI recurrence. Limited evidence remains on emergency-department use and outpatient burden in the same cohorts.",
      },
      {
        heading: "Elderly RWE",
        location: "Study B",
        text: "Study B is a single-arm chart review of patients aged ≥65 treated with an EGFR TKI. No comparative arm versus regional standard of care. Evidence gap on comparative effectiveness in the elderly is not closed.",
      },
      {
        heading: "PRO",
        location: "Study C",
        text: "Study C measures EORTC QLQ-C30 in a mixed-age trial population. Insufficient evidence on caregiver burden and on PRO in frail patients.",
      },
    ]),
    ...blocks("SRC-CDP-001", [
      {
        heading: "VEL-301",
        location: "CDP §4",
        text: "VEL-301 Phase III versus osimertinib addresses PFS in 2L EGFR-mutant NSCLC. Subgroup analysis in elderly is planned but not a powered comparative effectiveness question versus chemotherapy SoC.",
      },
    ]),
    ...blocks("SRC-HEOR-001", [
      {
        heading: "Models",
        location: "HEOR strategy",
        text: "Cost-effectiveness versus osimertinib is in build. We need to understand budget impact under IRA. Limited evidence on HCRU associated with recurrence feeds the model.",
      },
    ]),
    ...blocks("SRC-RWE-001", [
      {
        heading: "Registry",
        location: "RWE strategy",
        text: "The prospective Velmara registry will collect treatment, progression, survival, hospitalisations, sequencing and PROs. It does not include a concurrent SoC comparator in elderly patients.",
      },
    ]),
    ...blocks("SRC-MED-001", [
      {
        heading: "Congress presence",
        location: "Medical action plan",
        text: "Medical affairs wants a bigger congress presence in 2027. This is a dissemination preference, not an evidence need, but it was raised alongside the CNS evidence gap.",
      },
    ]),
  ];

  const fullText = (id: string) =>
    srcBlocks
      .filter((b) => b.source_id === id)
      .map((b) => b.text)
      .join("\n");

  const state = {
    asset: {
      id: "ASSET-VELMARA",
      name: "Velmara",
      inn: "velmaratinib",
      indication: "2L EGFR-mutant NSCLC",
      geography: "US + EU5",
      wizard_complete: true,
      tactics_unlocked: true,
    },
    objectives: [
      {
        id: "OBJ-REIMB",
        name: "Support reimbursement and HTA",
        description: "Generate decision-grade evidence for US payers and EU5 HTA.",
        lifecycle_stage: "peri-launch",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US + EU5",
        strategic_importance: 5,
        key_decision: "US national payer P&T and EU5 HTA filings",
        decision_date: "2027-03-31",
        owner: "T. Okonkwo",
      },
      {
        id: "OBJ-DIFF",
        name: "Demonstrate differentiated clinical value",
        description: "Position Velmara versus osimertinib and NX-441.",
        lifecycle_stage: "peri-launch",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US + EU5",
        strategic_importance: 5,
        key_decision: "Brand strategy lock",
        decision_date: "2026-12-15",
        owner: "M. Hale",
      },
      {
        id: "OBJ-ELDERLY",
        name: "Establish value in elderly and frail patients",
        description: "Answer the elderly SoC question that HTA and KOLs keep raising.",
        lifecycle_stage: "peri-launch",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US + EU5",
        strategic_importance: 5,
        key_decision: "HTA elderly subgroup package",
        decision_date: "2027-01-15",
        owner: "A. Rao",
      },
      {
        id: "OBJ-BURDEN",
        name: "Characterise burden of CNS disease and recurrence",
        description: "Clinical, HCRU and economic burden to feed models and medical.",
        lifecycle_stage: "peri-launch",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US + EU5",
        strategic_importance: 4,
        key_decision: "CEA/BIM input freeze",
        decision_date: "2026-11-30",
        owner: "A. Rao",
      },
      {
        id: "OBJ-SEQ",
        name: "Support treatment sequencing",
        description: "Where Velmara sits after osimertinib and versus NX-441.",
        lifecycle_stage: "lifecycle",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US + EU5",
        strategic_importance: 4,
        key_decision: "Medical sequencing narrative",
        decision_date: "2027-06-01",
        owner: "M. Hale",
      },
      {
        id: "OBJ-ACCESS",
        name: "Improve patient access",
        description: "Formulary, IRA net price, persistence RWE.",
        lifecycle_stage: "peri-launch",
        indication: "2L EGFR-mutant NSCLC",
        geography: "US",
        strategic_importance: 5,
        key_decision: "Aetna / UHC formulary",
        decision_date: "2026-12-01",
        owner: "T. Okonkwo",
      },
    ],
    sources: [
      {
        id: "SRC-INT-HEOR",
        filename: "IEGP_HEOR_interviews_Q3_2026.docx",
        title: "HEOR stakeholder interviews",
        source_type: "stakeholder_interview",
        stakeholder_function: "heor",
        ingested_at: AT,
        full_text: fullText("SRC-INT-HEOR"),
      },
      {
        id: "SRC-INT-MED",
        filename: "IEGP_Medical_KOL_interviews_Q3_2026.docx",
        title: "Medical affairs / KOL interviews",
        source_type: "stakeholder_interview",
        stakeholder_function: "medical_affairs",
        ingested_at: AT,
        full_text: fullText("SRC-INT-MED"),
      },
      {
        id: "SRC-INT-ACCESS",
        filename: "IEGP_Payer_adboard_Sep2026.pptx",
        title: "Payer advisory board",
        source_type: "advisory_board",
        stakeholder_function: "market_access",
        ingested_at: AT,
        full_text: fullText("SRC-INT-ACCESS"),
      },
      {
        id: "SRC-TLR-001",
        filename: "Velmara_TLR_evidence_landscape_2026.docx",
        title: "Targeted literature review — evidence landscape",
        source_type: "targeted_literature_review",
        stakeholder_function: "heor",
        ingested_at: AT,
        full_text: fullText("SRC-TLR-001"),
      },
      {
        id: "SRC-CDP-001",
        filename: "VEL_Clinical_Development_Plan_v4.pptx",
        title: "Clinical development plan",
        source_type: "clinical_development_plan",
        stakeholder_function: "clinical_development",
        ingested_at: AT,
        full_text: fullText("SRC-CDP-001"),
      },
      {
        id: "SRC-HEOR-001",
        filename: "Velmara_HEOR_value_evidence_strategy_2026.xlsx",
        title: "HEOR value evidence strategy",
        source_type: "heor_strategy",
        stakeholder_function: "heor",
        ingested_at: AT,
        full_text: fullText("SRC-HEOR-001"),
      },
      {
        id: "SRC-RWE-001",
        filename: "Velmara_RWE_strategy_2026.docx",
        title: "RWE / epidemiology strategy",
        source_type: "rwe_strategy",
        stakeholder_function: "rwe",
        ingested_at: AT,
        full_text: fullText("SRC-RWE-001"),
      },
      {
        id: "SRC-MED-001",
        filename: "Velmara_Medical_action_plan_2027.pptx",
        title: "Medical action plan",
        source_type: "medical_strategy",
        stakeholder_function: "medical_affairs",
        ingested_at: AT,
        full_text: fullText("SRC-MED-001"),
      },
    ],
    blocks: srcBlocks,
    needs: [
      need("NEED-001", {
        statement: "Need to understand the economic burden associated with recurrence after velmaratinib.",
        domain: "economics",
        stakeholder: "heor",
        objective_id: "OBJ-BURDEN",
        decision_supported: "CEA/BIM input freeze",
        geography: "US + EU5",
        population: "Patients with recurrence after 2L EGFR TKI",
        intervention: "Velmara",
        comparator: "n/a",
        outcome: "Direct medical costs of recurrence",
        timing: "Q4 2026",
        source_id: "SRC-INT-HEOR",
        source_quote: "We need to understand the economic burden associated with recurrence after velmaratinib.",
        status: "accepted",
        who: rao,
      }),
      need("NEED-002", {
        statement: "Limited evidence characterises direct costs of repeat procedures in routine practice.",
        domain: "economics",
        stakeholder: "heor",
        objective_id: "OBJ-BURDEN",
        decision_supported: "CEA/BIM input freeze",
        geography: "US",
        population: "Routine-care NSCLC with recurrence",
        intervention: "Velmara",
        comparator: "n/a",
        outcome: "Repeat procedures, subsequent treatment cost",
        timing: "Q4 2026",
        source_id: "SRC-INT-HEOR",
        source_quote: "Limited evidence characterises direct costs of repeat procedures in routine practice.",
        status: "accepted",
        who: rao,
      }),
      need("NEED-003", {
        statement: "Need comparative effectiveness of Velmara versus regional standard of care in elderly patients with advanced EGFR-mutant NSCLC.",
        domain: "comparative_effectiveness",
        stakeholder: "hta",
        objective_id: "OBJ-ELDERLY",
        decision_supported: "HTA elderly subgroup package",
        geography: "EU5",
        population: "Aged ≥65, advanced EGFR-mutant NSCLC",
        intervention: "Velmara",
        comparator: "Regional SoC (chemo / immuno)",
        outcome: "OS, PFS, ORR",
        timing: "Jan 2027",
        source_id: "SRC-INT-HEOR",
        source_quote: "whether we have comparative effectiveness of Velmara versus regional standard of care in elderly patients",
        status: "accepted",
        who: rao,
      }),
      need("NEED-004", {
        statement: "Insufficient evidence in patients aged 65 and over — still a candidate perception until pressure-tested against the TLR and RWE plan.",
        domain: "subpopulations",
        stakeholder: "heor",
        objective_id: "OBJ-ELDERLY",
        decision_supported: "HTA elderly subgroup package",
        geography: "US + EU5",
        population: "Aged ≥65",
        intervention: "Velmara",
        comparator: "Unspecified",
        outcome: "Outcomes in elderly",
        timing: "2027",
        source_id: "SRC-INT-HEOR",
        source_quote: "We don't have enough evidence in patients aged 65 and over.",
        status: "candidate",
        who: null,
      }),
      need("NEED-005", {
        statement: "Need to know intracranial outcomes in patients with brain metastases.",
        domain: "efficacy",
        stakeholder: "medical_affairs",
        objective_id: "OBJ-BURDEN",
        decision_supported: "Medical CNS narrative",
        geography: "US + EU5",
        population: "Brain metastases",
        intervention: "Velmara",
        comparator: "Prior EGFR TKI",
        outcome: "Intracranial ORR and duration",
        timing: "2027 H1",
        source_id: "SRC-INT-MED",
        source_quote: "KOLs need to know intracranial outcomes.",
        status: "accepted",
        who: hale,
      }),
      need("NEED-006", {
        statement: "Limited evidence on CNS response and duration in brain metastases remains an open question.",
        domain: "long_term_outcomes",
        stakeholder: "medical_affairs",
        objective_id: "OBJ-BURDEN",
        decision_supported: "Medical CNS narrative",
        geography: "US + EU5",
        population: "CNS metastases",
        intervention: "Velmara",
        comparator: "n/a",
        outcome: "CNS DOR",
        timing: "2027 H1",
        source_id: "SRC-INT-MED",
        source_quote: "Limited evidence on CNS response and duration in patients with brain metastases remains an open question for medical affairs.",
        status: "accepted",
        who: hale,
      }),
      need("NEED-007", {
        statement: "Need to characterise real-world treatment sequencing after osimertinib failure.",
        domain: "treatment_sequencing",
        stakeholder: "medical_affairs",
        objective_id: "OBJ-SEQ",
        decision_supported: "Medical sequencing narrative",
        geography: "US + EU5",
        population: "Post-osimertinib 2L",
        intervention: "Velmara",
        comparator: "NX-441 and other 2L options",
        outcome: "Treatment patterns",
        timing: "2027",
        source_id: "SRC-INT-MED",
        source_quote: "We need to characterise real-world treatment sequencing after osimertinib failure.",
        status: "accepted",
        who: hale,
      }),
      need("NEED-008", {
        statement: "Need 6-month discontinuation and persistence in routine care for US national payers.",
        domain: "adherence",
        stakeholder: "market_access",
        objective_id: "OBJ-ACCESS",
        decision_supported: "Aetna / UHC formulary",
        geography: "US",
        population: "Commercial and Medicare",
        intervention: "Velmara",
        comparator: "Osimertinib persistence benchmarks",
        outcome: "6-month discontinuation",
        timing: "Dec 2026",
        source_id: "SRC-INT-ACCESS",
        source_quote: "Aetna and UnitedHealthcare need to understand 6-month discontinuation in routine care.",
        status: "accepted",
        who: okonkwo,
      }),
      need("NEED-009", {
        statement: "Need to quantify IRA net-price exposure for Velmara.",
        domain: "budget_impact",
        stakeholder: "market_access",
        objective_id: "OBJ-ACCESS",
        decision_supported: "IRA scenario in BIM",
        geography: "US",
        population: "Medicare",
        intervention: "Velmara",
        comparator: "Unadjusted WAC BIM",
        outcome: "Net price / BIM delta",
        timing: "Q4 2026",
        source_id: "SRC-INT-ACCESS",
        source_quote: "We need to quantify IRA net-price exposure for Velmara.",
        status: "accepted",
        who: okonkwo,
      }),
      need("NEED-010", {
        statement: "Limited evidence remains on emergency-department use and outpatient burden after EGFR TKI recurrence.",
        domain: "hcru",
        stakeholder: "heor",
        objective_id: "OBJ-BURDEN",
        decision_supported: "CEA/BIM input freeze",
        geography: "US",
        population: "Recurrence after EGFR TKI",
        intervention: "n/a",
        comparator: "n/a",
        outcome: "ED visits, outpatient HCRU",
        timing: "Q4 2026",
        source_id: "SRC-TLR-001",
        source_quote: "Limited evidence remains on emergency-department use and outpatient burden in the same cohorts.",
        status: "accepted",
        who: rao,
      }),
      need("NEED-011", {
        statement: "Evidence gap on comparative effectiveness in the elderly is not closed by single-arm chart reviews.",
        domain: "comparative_effectiveness",
        stakeholder: "heor",
        objective_id: "OBJ-ELDERLY",
        decision_supported: "HTA elderly subgroup package",
        geography: "US + EU5",
        population: "Aged ≥65",
        intervention: "EGFR TKI",
        comparator: "Regional SoC",
        outcome: "Comparative OS/PFS",
        timing: "2027",
        source_id: "SRC-TLR-001",
        source_quote: "No comparative arm versus regional standard of care. Evidence gap on comparative effectiveness in the elderly is not closed.",
        status: "accepted",
        who: rao,
      }),
      need("NEED-012", {
        statement: "Insufficient evidence on caregiver burden and on PRO in frail patients.",
        domain: "caregiver_burden",
        stakeholder: "patient_engagement",
        objective_id: "OBJ-BURDEN",
        decision_supported: "Patient-centred value story",
        geography: "US + EU5",
        population: "Frail / elderly + caregivers",
        intervention: "Velmara",
        comparator: "n/a",
        outcome: "Caregiver burden, PRO",
        timing: "2027",
        source_id: "SRC-TLR-001",
        source_quote: "Insufficient evidence on caregiver burden and on PRO in frail patients.",
        status: "accepted",
        who: hale,
      }),
      need("NEED-013", {
        statement: "Need powered comparative effectiveness versus chemotherapy SoC in elderly — VEL-301 elderly subgroup is not that question.",
        domain: "comparative_effectiveness",
        stakeholder: "clinical_development",
        objective_id: "OBJ-ELDERLY",
        decision_supported: "HTA elderly subgroup package",
        geography: "Global",
        population: "Elderly 2L EGFR NSCLC",
        intervention: "Velmara",
        comparator: "Chemotherapy SoC",
        outcome: "PFS/OS",
        timing: "2027",
        source_id: "SRC-CDP-001",
        source_quote: "Subgroup analysis in elderly is planned but not a powered comparative effectiveness question versus chemotherapy SoC.",
        status: "accepted",
        who: chen,
      }),
      need("NEED-014", {
        statement: "Need to understand budget impact under IRA.",
        domain: "budget_impact",
        stakeholder: "heor",
        objective_id: "OBJ-REIMB",
        decision_supported: "US P&T",
        geography: "US",
        population: "Medicare",
        intervention: "Velmara",
        comparator: "Osimertinib",
        outcome: "BIM",
        timing: "Q4 2026",
        source_id: "SRC-HEOR-001",
        source_quote: "We need to understand budget impact under IRA.",
        status: "accepted",
        who: rao,
      }),
      need("NEED-015", {
        statement: "Limited evidence on HCRU associated with recurrence feeds the economic model.",
        domain: "hcru",
        stakeholder: "heor",
        objective_id: "OBJ-BURDEN",
        decision_supported: "CEA/BIM input freeze",
        geography: "US + EU5",
        population: "Recurrence",
        intervention: "n/a",
        comparator: "n/a",
        outcome: "HCRU inputs",
        timing: "Nov 2026",
        source_id: "SRC-HEOR-001",
        source_quote: "Limited evidence on HCRU associated with recurrence feeds the model.",
        status: "accepted",
        who: rao,
      }),
      need("NEED-016", {
        statement: "Need real-world treatment patterns, survival, hospitalisations, sequencing and PROs from a prospective registry — without treating the registry as a SoC comparator.",
        domain: "treatment_patterns",
        stakeholder: "rwe",
        objective_id: "OBJ-SEQ",
        decision_supported: "Integrated RWE package",
        geography: "US + EU5",
        population: "Velmara-treated 2L",
        intervention: "Velmara",
        comparator: "None in registry",
        outcome: "Patterns, OS, HCRU, PRO",
        timing: "2027–2028",
        source_id: "SRC-RWE-001",
        source_quote: "The prospective Velmara registry will collect treatment, progression, survival, hospitalisations, sequencing and PROs.",
        status: "accepted",
        who: chen,
      }),
      need("NEED-017", {
        statement: "Need a bigger congress presence in 2027 — candidate only; likely a dissemination issue rather than an evidence gap.",
        domain: "implementation",
        stakeholder: "medical_affairs",
        objective_id: "OBJ-DIFF",
        decision_supported: "Medical action plan",
        geography: "Global",
        population: "n/a",
        intervention: "n/a",
        comparator: "n/a",
        outcome: "Congress footprint",
        timing: "2027",
        source_id: "SRC-MED-001",
        source_quote: "Medical affairs wants a bigger congress presence in 2027.",
        status: "candidate",
        who: null,
      }),
      need("NEED-018", {
        statement: "Need QoL / PRO in routine care, not only mixed-age trial EORTC.",
        domain: "qol_pro",
        stakeholder: "medical_affairs",
        objective_id: "OBJ-BURDEN",
        decision_supported: "Patient-centred value story",
        geography: "US + EU5",
        population: "Routine-care 2L",
        intervention: "Velmara",
        comparator: "n/a",
        outcome: "PROs",
        timing: "2027",
        source_id: "SRC-TLR-001",
        source_quote: "Study C measures EORTC QLQ-C30 in a mixed-age trial population.",
        status: "accepted",
        who: hale,
      }),
      need("NEED-019", {
        statement: "Need long-term overall survival beyond the VEL-301 primary analysis.",
        domain: "long_term_outcomes",
        stakeholder: "clinical_development",
        objective_id: "OBJ-DIFF",
        decision_supported: "Label and value story",
        geography: "Global",
        population: "VEL-301 ITT",
        intervention: "Velmara",
        comparator: "Osimertinib",
        outcome: "OS",
        timing: "2028",
        source_id: "SRC-CDP-001",
        source_quote: "VEL-301 Phase III versus osimertinib addresses PFS in 2L EGFR-mutant NSCLC.",
        status: "accepted",
        who: chen,
      }),
      need("NEED-020", {
        statement: "Need natural-history clinical burden of recurrence (progression, subsequent therapy) as distinct from cost.",
        domain: "natural_history",
        stakeholder: "epidemiology",
        objective_id: "OBJ-BURDEN",
        decision_supported: "CEA/BIM input freeze",
        geography: "US + EU5",
        population: "Recurrence after EGFR TKI",
        intervention: "n/a",
        comparator: "n/a",
        outcome: "Clinical course after recurrence",
        timing: "Q4 2026",
        source_id: "SRC-HEOR-001",
        source_quote: "Limited evidence on HCRU associated with recurrence feeds the model.",
        status: "accepted",
        who: rao,
      }),
      need("NEED-021", {
        statement: "Need safety characterisation of ILD and QT in routine care — candidate, not yet pressure-tested.",
        domain: "safety",
        stakeholder: "regulatory",
        objective_id: "OBJ-DIFF",
        decision_supported: "Label / REMS discussion",
        geography: "US",
        population: "All exposed",
        intervention: "Velmara",
        comparator: "n/a",
        outcome: "ILD, QT",
        timing: "2027",
        source_id: "SRC-MED-001",
        source_quote: "This is a dissemination preference, not an evidence need, but it was raised alongside the CNS evidence gap.",
        status: "candidate",
        who: null,
      }),
      need("NEED-022", {
        statement: "Need pivotal comparative PFS versus osimertinib in 2L EGFR-mutant NSCLC.",
        domain: "efficacy",
        stakeholder: "clinical_development",
        objective_id: "OBJ-DIFF",
        decision_supported: "Label and value story",
        geography: "Global",
        population: "2L EGFR-mutant NSCLC",
        intervention: "Velmara",
        comparator: "Osimertinib",
        outcome: "PFS",
        timing: "2026",
        source_id: "SRC-CDP-001",
        source_quote: "VEL-301 Phase III versus osimertinib addresses PFS in 2L EGFR-mutant NSCLC.",
        status: "accepted",
        who: lead,
      }),
    ],
    gaps: [
      {
        id: "GAP-ELDERLY-CE",
        name: "Comparative effectiveness of Velmara versus regional SoC in elderly patients, including HTA-relevant outcomes",
        statement:
          "Limited evidence on comparative effectiveness of velmaratinib versus regional standard of care in elderly patients with advanced EGFR-mutant NSCLC.",
        domain: "comparative_effectiveness",
        objective_id: "OBJ-ELDERLY",
        status: "validated_partial",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...rao, "Pressure-tested against TLR Study B and VEL-301 elderly subgroup. Comparator missing."),
      },
      {
        id: "GAP-RECUR-ECON",
        name: "Economic burden of recurrence after velmaratinib, including costs of repeat procedures and subsequent treatment",
        statement:
          "Need to understand clinical and economic burden associated with recurrence — costs of repeat procedures and subsequent treatment remain thin.",
        domain: "economics",
        objective_id: "OBJ-BURDEN",
        status: "validated_partial",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...rao, "Clinical burden and some HCRU exist; direct costs remain residual."),
      },
      {
        id: "GAP-CNS",
        name: "Intracranial response and duration in patients with brain metastases",
        statement:
          "Limited evidence on intracranial response and duration in patients with brain metastases.",
        domain: "efficacy",
        objective_id: "OBJ-BURDEN",
        status: "validated_open",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...hale, "No tactic adequately answers CNS DOR. Registry collects progression but not dedicated intracranial package."),
      },
      {
        id: "GAP-SEQ",
        name: "Real-world treatment sequencing after osimertinib failure, including Velmara versus NX-441",
        statement:
          "Need real-world treatment sequencing after osimertinib failure, including where Velmara sits versus NX-441.",
        domain: "treatment_sequencing",
        objective_id: "OBJ-SEQ",
        status: "validated_partial",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...chen, "Registry will capture patterns; NX-441 comparator is thin."),
      },
      {
        id: "GAP-HCRU",
        name: "HCRU after recurrence, including hospitalisations, ED use, and outpatient burden",
        statement:
          "Limited evidence on hospitalisations, ED use and outpatient burden associated with recurrence.",
        domain: "hcru",
        objective_id: "OBJ-BURDEN",
        status: "validated_partial",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...rao, "Study A + registry cover hospitalisations; ED/outpatient only partial."),
      },
      {
        id: "GAP-QOL",
        name: "QoL and PRO in routine care, including frail patients",
        statement:
          "Need PROs in routine care, including frail patients, not only mixed-age trial EORTC.",
        domain: "qol_pro",
        objective_id: "OBJ-BURDEN",
        status: "validated_partial",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...hale, "Registry collects PROs; frail/caregiver still open."),
      },
      {
        id: "GAP-PERSIST",
        name: "Six-month discontinuation and persistence in US routine care",
        statement:
          "Need 6-month discontinuation / persistence in US routine care for national payer P&T.",
        domain: "adherence",
        objective_id: "OBJ-ACCESS",
        status: "validated_open",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...okonkwo, "No completed tactic answers Aetna/UHC. Planned claims study not started."),
      },
      {
        id: "GAP-IRA",
        name: "Budget impact under IRA negotiated-price scenarios",
        statement:
          "Need budget-impact under IRA negotiated-price scenarios.",
        domain: "budget_impact",
        objective_id: "OBJ-ACCESS",
        status: "validated_open",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...okonkwo, "BIM exists at WAC; IRA scenario is a planned tactic."),
      },
      {
        id: "GAP-CAREGIVER",
        name: "Caregiver burden in elderly and frail Velmara use",
        statement:
          "Insufficient evidence on caregiver burden in elderly/frail Velmara use.",
        domain: "caregiver_burden",
        objective_id: "OBJ-BURDEN",
        status: "validated_open",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...hale, "No tactic in flight."),
      },
      {
        id: "GAP-OS",
        name: "Overall survival beyond the VEL-301 primary PFS analysis",
        statement:
          "Need overall survival beyond the VEL-301 primary PFS analysis.",
        domain: "long_term_outcomes",
        objective_id: "OBJ-DIFF",
        status: "validated_partial",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...chen, "LTFU planned; not yet available for the 2026 value story."),
      },
      {
        id: "GAP-CONGRESS",
        name: "Congress presence in 2027",
        statement:
          "Medical affairs wants a bigger congress presence in 2027.",
        domain: "implementation",
        objective_id: "OBJ-DIFF",
        status: "excluded",
        exclusion_reason: "communication_issue",
        exclusion_note:
          "Dissemination preference, not an evidence gap. Keep the CNS need. A congress abstract can still be a tactic of type dissemination.",
        status_lock: lock(...lead, "Excluded: communication issue, not an IEGP gap."),
      },
      {
        id: "GAP-PFS-TRIAL",
        name: "Pivotal PFS versus osimertinib in 2L EGFR-mutant NSCLC",
        statement:
          "Pivotal comparative PFS versus osimertinib in 2L EGFR-mutant NSCLC.",
        domain: "efficacy",
        objective_id: "OBJ-DIFF",
        status: "validated_addressed",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: lock(...lead, "VEL-301 addresses this question. Human lock after pressure-test."),
      },
      {
        id: "GAP-ILD",
        name: "ILD and QT incidence in routine care, including monitoring outside academic centres",
        statement:
          "Need safety characterisation of ILD and QT in routine care — extracted as a candidate, not yet accepted.",
        domain: "safety",
        objective_id: "OBJ-DIFF",
        status: "candidate",
        exclusion_reason: null,
        exclusion_note: null,
        status_lock: unlocked(),
      },
    ],
    need_gap_links: [
      { need_id: "NEED-003", gap_id: "GAP-ELDERLY-CE", role: "primary" },
      { need_id: "NEED-011", gap_id: "GAP-ELDERLY-CE", role: "supporting" },
      { need_id: "NEED-013", gap_id: "GAP-ELDERLY-CE", role: "supporting" },
      { need_id: "NEED-001", gap_id: "GAP-RECUR-ECON", role: "primary" },
      { need_id: "NEED-002", gap_id: "GAP-RECUR-ECON", role: "supporting" },
      { need_id: "NEED-005", gap_id: "GAP-CNS", role: "primary" },
      { need_id: "NEED-006", gap_id: "GAP-CNS", role: "supporting" },
      { need_id: "NEED-007", gap_id: "GAP-SEQ", role: "primary" },
      { need_id: "NEED-016", gap_id: "GAP-SEQ", role: "supporting" },
      { need_id: "NEED-010", gap_id: "GAP-HCRU", role: "primary" },
      { need_id: "NEED-015", gap_id: "GAP-HCRU", role: "supporting" },
      { need_id: "NEED-018", gap_id: "GAP-QOL", role: "primary" },
      { need_id: "NEED-008", gap_id: "GAP-PERSIST", role: "primary" },
      { need_id: "NEED-009", gap_id: "GAP-IRA", role: "primary" },
      { need_id: "NEED-014", gap_id: "GAP-IRA", role: "supporting" },
      { need_id: "NEED-012", gap_id: "GAP-CAREGIVER", role: "primary" },
      { need_id: "NEED-019", gap_id: "GAP-OS", role: "primary" },
      { need_id: "NEED-017", gap_id: "GAP-CONGRESS", role: "primary" },
      { need_id: "NEED-020", gap_id: "GAP-RECUR-ECON", role: "supporting" },
      { need_id: "NEED-021", gap_id: "GAP-ILD", role: "primary" },
      { need_id: "NEED-022", gap_id: "GAP-PFS-TRIAL", role: "primary" },
    ],
    tactics: [
      tactic("TAC-VEL-301", {
        name: "VEL-301 Phase III vs osimertinib",
        type: "phase3_trial",
        description: "Pivotal 2L EGFR-mutant NSCLC trial. Primary PFS. Elderly subgroup not powered vs chemo SoC.",
        evidence_question: "Does Velmara improve PFS versus osimertinib?",
        population: "2L EGFR-mutant NSCLC",
        intervention: "Velmara",
        comparator: "Osimertinib",
        outcomes: "PFS, OS, ORR, safety",
        geography: "Global",
        data_source: "VEL-301",
        study_design: "Randomised Phase III",
        lifecycle_stage: "peri-launch",
        status: "ongoing",
        start_date: "2024-03-01",
        evidence_available: "2026-11-01",
        owner: "ClinDev",
        function: "clinical_development",
        budget: "$180M",
        intended_use: "Label + HTA clinical package",
        who: chen,
      }),
      tactic("TAC-REG", {
        name: "Prospective Velmara registry",
        type: "registry",
        description:
          "Collects treatment, progression, survival, hospitalisations, sequencing and PROs. No concurrent SoC comparator in elderly.",
        evidence_question: "What happens to Velmara-treated patients in routine care?",
        population: "Velmara-treated 2L",
        intervention: "Velmara",
        comparator: "None",
        outcomes: "Treatment patterns, OS, HCRU, PRO",
        geography: "US + EU5",
        data_source: "VEL-REG-2026",
        study_design: "Prospective registry",
        lifecycle_stage: "peri-launch",
        status: "ongoing",
        start_date: "2026-04-01",
        evidence_available: "2027-09-01",
        owner: "L. Chen",
        function: "rwe",
        budget: "$4.2M",
        intended_use: "Multi-gap RWE package",
        who: chen,
      }),
      tactic("TAC-ELDERLY-RWE", {
        name: "Retrospective RWE in patients aged ≥65",
        type: "chart_review",
        description:
          "Single-arm chart review of velmaratinib-treated patients aged ≥65. No regional SoC comparator.",
        evidence_question: "What are outcomes on Velmara in elderly patients?",
        population: "Aged ≥65, Velmara-treated",
        intervention: "Velmara",
        comparator: "None",
        outcomes: "rwPFS, OS, safety",
        geography: "US",
        data_source: "US EHR / chart",
        study_design: "Retrospective single-arm",
        lifecycle_stage: "peri-launch",
        status: "ongoing",
        start_date: "2026-01-15",
        evidence_available: "2026-10-01",
        owner: "L. Chen",
        function: "rwe",
        budget: "$0.9M",
        intended_use: "HTA elderly support — insufficient alone",
        who: chen,
      }),
      tactic("TAC-NH", {
        name: "Natural-history RWE after recurrence",
        type: "natural_history_study",
        description: "Clinical course after EGFR TKI recurrence: progression, subsequent therapy.",
        evidence_question: "What is the clinical burden of recurrence?",
        population: "Recurrence after EGFR TKI",
        intervention: "n/a",
        comparator: "n/a",
        outcomes: "Subsequent therapy, time-to-event",
        geography: "US",
        data_source: "Claims + EHR",
        study_design: "Retrospective cohort",
        lifecycle_stage: "peri-launch",
        status: "completed",
        start_date: "2025-02-01",
        evidence_available: "2026-03-01",
        owner: "Epidemiology",
        function: "epidemiology",
        budget: "$0.6M",
        intended_use: "CEA clinical inputs",
        who: rao,
      }),
      tactic("TAC-HCRU", {
        name: "HCRU study after recurrence",
        type: "hcru_study",
        description: "Hospitalisations after recurrence (Study A analogue). ED/outpatient incompletely captured.",
        evidence_question: "What HCRU follows recurrence?",
        population: "Recurrence after EGFR TKI",
        intervention: "n/a",
        comparator: "n/a",
        outcomes: "Hospitalisations; limited ED/OP",
        geography: "US",
        data_source: "Claims",
        study_design: "Retrospective HCRU",
        lifecycle_stage: "peri-launch",
        status: "completed",
        start_date: "2025-06-01",
        evidence_available: "2026-04-15",
        owner: "A. Rao",
        function: "heor",
        budget: "$0.5M",
        intended_use: "CEA HCRU inputs",
        who: rao,
      }),
      tactic("TAC-CEA", {
        name: "Cost-effectiveness vs osimertinib",
        type: "cea",
        description: "Partitioned survival CEA. Waiting on recurrence cost and IRA BIM.",
        evidence_question: "Is Velmara cost-effective vs osimertinib?",
        population: "2L EGFR-mutant NSCLC",
        intervention: "Velmara",
        comparator: "Osimertinib",
        outcomes: "ICER, QALYs",
        geography: "US + EU5",
        data_source: "Trial + RWE inputs",
        study_design: "CEA",
        lifecycle_stage: "peri-launch",
        status: "ongoing",
        start_date: "2026-02-01",
        evidence_available: "2027-02-01",
        owner: "A. Rao",
        function: "heor",
        budget: "$0.4M",
        intended_use: "HTA economic dossier",
        who: rao,
      }),
      tactic("TAC-BIM", {
        name: "Budget-impact model — IRA scenario",
        type: "budget_impact_model",
        description: "WAC BIM exists. IRA negotiated-price scenario is planned, not built.",
        evidence_question: "What is US budget impact under IRA?",
        population: "Medicare",
        intervention: "Velmara",
        comparator: "Osimertinib",
        outcomes: "BIM",
        geography: "US",
        data_source: "Internal forecasts",
        study_design: "BIM",
        lifecycle_stage: "peri-launch",
        status: "planned",
        start_date: "2026-10-01",
        evidence_available: "2026-12-15",
        owner: "T. Okonkwo",
        function: "market_access",
        budget: "$0.15M",
        intended_use: "P&T",
        who: okonkwo,
      }),
      tactic("TAC-CLAIMS", {
        name: "US claims persistence study",
        type: "rwe_study",
        description: "6-month discontinuation for Aetna/UHC. Planned, not started.",
        evidence_question: "What is 6-month discontinuation in routine care?",
        population: "US commercial + Medicare",
        intervention: "Velmara",
        comparator: "Osimertinib benchmarks",
        outcomes: "Discontinuation, persistence",
        geography: "US",
        data_source: "National claims",
        study_design: "Retrospective persistence",
        lifecycle_stage: "peri-launch",
        status: "planned",
        start_date: "2026-11-01",
        evidence_available: "2027-04-01",
        owner: "L. Chen",
        function: "rwe",
        budget: "$0.7M",
        intended_use: "National payer P&T",
        who: okonkwo,
      }),
      tactic("TAC-SLR", {
        name: "SLR of elderly EGFR TKI outcomes",
        type: "slr",
        description: "Landscaping SLR. Confirms the comparator gap; does not close it.",
        evidence_question: "What published evidence exists in elderly EGFR TKI?",
        population: "Elderly EGFR-mutant NSCLC",
        intervention: "EGFR TKIs",
        comparator: "Mixed",
        outcomes: "Published OS/PFS",
        geography: "Global",
        data_source: "Literature",
        study_design: "SLR",
        lifecycle_stage: "peri-launch",
        status: "completed",
        start_date: "2025-09-01",
        evidence_available: "2026-02-01",
        owner: "A. Rao",
        function: "heor",
        budget: "$0.12M",
        intended_use: "Pressure-test, not coverage",
        who: rao,
      }),
      tactic("TAC-LTFU", {
        name: "VEL-301 long-term OS follow-up",
        type: "long_term_followup",
        description: "Protocol-defined OS follow-up after primary PFS.",
        evidence_question: "Does OS separate with longer follow-up?",
        population: "VEL-301 ITT",
        intervention: "Velmara",
        comparator: "Osimertinib",
        outcomes: "OS",
        geography: "Global",
        data_source: "VEL-301",
        study_design: "LTFU",
        lifecycle_stage: "lifecycle",
        status: "planned",
        start_date: "2027-01-01",
        evidence_available: "2028-06-01",
        owner: "ClinDev",
        function: "clinical_development",
        budget: "In trial budget",
        intended_use: "Label update + value story",
        who: chen,
      }),
      tactic("TAC-PUB-PFS", {
        name: "VEL-301 primary manuscript",
        type: "publication",
        description: "Primary PFS publication. Dissemination tactic; does not create new evidence.",
        evidence_question: "Communicate VEL-301 PFS.",
        population: "VEL-301 ITT",
        intervention: "Velmara",
        comparator: "Osimertinib",
        outcomes: "PFS",
        geography: "Global",
        data_source: "VEL-301",
        study_design: "Manuscript",
        lifecycle_stage: "peri-launch",
        status: "planned",
        start_date: "2026-11-15",
        evidence_available: "2027-03-01",
        owner: "SciComms",
        function: "medical_affairs",
        budget: "$0.08M",
        intended_use: "Dissemination of addressed PFS gap",
        who: hale,
      }),
      tactic("TAC-SURVEY", {
        name: "Patient / caregiver survey (proposed)",
        type: "patient_survey",
        description: "Human-authored proposal to close caregiver + frail PRO residual. Not yet accepted onto the roadmap.",
        evidence_question: "What is caregiver burden and frail-patient PRO on Velmara?",
        population: "Elderly/frail + caregivers",
        intervention: "Velmara",
        comparator: "n/a",
        outcomes: "Caregiver burden, PRO",
        geography: "US + EU5",
        data_source: "Primary survey",
        study_design: "Cross-sectional survey",
        lifecycle_stage: "lifecycle",
        status: "proposed",
        start_date: null,
        evidence_available: null,
        owner: "Medical affairs",
        function: "patient_engagement",
        budget: "$0.35M",
        intended_use: "Patient-centred value story",
        who: null,
      }),
    ],
    coverages: [
      coverage({
        id: "COV-EL-RWE",
        gap_id: "GAP-ELDERLY-CE",
        tactic_id: "TAC-ELDERLY-RWE",
        overall: "partial",
        rationale:
          "Population, treatment, clinical outcomes and real-world setting: yes. Comparator and therefore comparative effectiveness: no. Overall partial.",
        who: rao,
        values: {
          relevance: "partial",
          population: "yes",
          intervention: "yes",
          comparator: "no",
          outcomes: "yes",
          geography: "partial",
          setting: "yes",
          timing: "yes",
          methodology: "partial",
          decision_utility: "no",
        },
      }),
      coverage({
        id: "COV-EL-301",
        gap_id: "GAP-ELDERLY-CE",
        tactic_id: "TAC-VEL-301",
        overall: "limited",
        rationale: "Elderly subgroup vs osimertinib, not vs regional chemo SoC. Not the HTA question.",
        who: rao,
        values: {
          relevance: "partial",
          population: "partial",
          intervention: "yes",
          comparator: "no",
          outcomes: "yes",
          geography: "yes",
          setting: "no",
          timing: "yes",
          methodology: "yes",
          decision_utility: "partial",
        },
      }),
      coverage({
        id: "COV-EL-SLR",
        gap_id: "GAP-ELDERLY-CE",
        tactic_id: "TAC-SLR",
        overall: "limited",
        rationale: "SLR confirms the gap. Existence of a publication is not coverage.",
        who: rao,
        values: {
          relevance: "partial",
          population: "yes",
          intervention: "partial",
          comparator: "no",
          outcomes: "partial",
          geography: "yes",
          setting: "partial",
          timing: "yes",
          methodology: "yes",
          decision_utility: "partial",
        },
      }),
      coverage({
        id: "COV-RE-NH",
        gap_id: "GAP-RECUR-ECON",
        tactic_id: "TAC-NH",
        overall: "partial",
        rationale: "Clinical burden of recurrence addressed. Direct economic costs not measured.",
        who: rao,
        values: {
          relevance: "partial",
          population: "yes",
          intervention: "yes",
          comparator: "unknown",
          outcomes: "partial",
          geography: "partial",
          setting: "yes",
          timing: "yes",
          methodology: "yes",
          decision_utility: "partial",
        },
      }),
      coverage({
        id: "COV-RE-HCRU",
        gap_id: "GAP-RECUR-ECON",
        tactic_id: "TAC-HCRU",
        overall: "partial",
        rationale: "HCRU (hospitalisations) partial. Repeat procedure and subsequent treatment costs remain.",
        who: rao,
        values: {
          relevance: "partial",
          population: "yes",
          intervention: "yes",
          comparator: "unknown",
          outcomes: "partial",
          geography: "partial",
          setting: "yes",
          timing: "yes",
          methodology: "yes",
          decision_utility: "partial",
        },
      }),
      coverage({
        id: "COV-SEQ-REG",
        gap_id: "GAP-SEQ",
        tactic_id: "TAC-REG",
        overall: "partial",
        rationale: "Registry captures Velmara sequencing. NX-441 concurrent comparison is thin.",
        who: chen,
        values: {
          relevance: "yes",
          population: "yes",
          intervention: "yes",
          comparator: "no",
          outcomes: "yes",
          geography: "yes",
          setting: "yes",
          timing: "partial",
          methodology: "yes",
          decision_utility: "partial",
        },
      }),
      coverage({
        id: "COV-HCRU-REG",
        gap_id: "GAP-HCRU",
        tactic_id: "TAC-REG",
        overall: "partial",
        rationale: "Hospitalisations collected. ED/outpatient not fully specified.",
        who: chen,
        values: {
          relevance: "yes",
          population: "yes",
          intervention: "yes",
          comparator: "unknown",
          outcomes: "partial",
          geography: "yes",
          setting: "yes",
          timing: "partial",
          methodology: "yes",
          decision_utility: "partial",
        },
      }),
      coverage({
        id: "COV-HCRU-STUDY",
        gap_id: "GAP-HCRU",
        tactic_id: "TAC-HCRU",
        overall: "partial",
        rationale: "Study A analogue: hospitalisations yes; ED/OP limited.",
        who: rao,
        values: {
          relevance: "yes",
          population: "yes",
          intervention: "yes",
          comparator: "unknown",
          outcomes: "partial",
          geography: "partial",
          setting: "yes",
          timing: "yes",
          methodology: "yes",
          decision_utility: "partial",
        },
      }),
      coverage({
        id: "COV-QOL-REG",
        gap_id: "GAP-QOL",
        tactic_id: "TAC-REG",
        overall: "partial",
        rationale: "PROs in registry. Frail-specific and caregiver not in the instrument set.",
        who: hale,
        values: {
          relevance: "yes",
          population: "partial",
          intervention: "yes",
          comparator: "unknown",
          outcomes: "partial",
          geography: "yes",
          setting: "yes",
          timing: "partial",
          methodology: "partial",
          decision_utility: "partial",
        },
      }),
      coverage({
        id: "COV-OS-LTFU",
        gap_id: "GAP-OS",
        tactic_id: "TAC-LTFU",
        overall: "partial",
        rationale: "Right question, wrong time for the 2026 value story.",
        who: chen,
        values: {
          relevance: "yes",
          population: "yes",
          intervention: "yes",
          comparator: "yes",
          outcomes: "yes",
          geography: "yes",
          setting: "partial",
          timing: "no",
          methodology: "yes",
          decision_utility: "partial",
        },
      }),
      coverage({
        id: "COV-PFS-301",
        gap_id: "GAP-PFS-TRIAL",
        tactic_id: "TAC-VEL-301",
        overall: "full",
        rationale: "This is the question VEL-301 was built to answer.",
        who: lead,
        values: {
          relevance: "yes",
          population: "yes",
          intervention: "yes",
          comparator: "yes",
          outcomes: "yes",
          geography: "yes",
          setting: "partial",
          timing: "yes",
          methodology: "yes",
          decision_utility: "yes",
        },
      }),
      coverage({
        id: "COV-PFS-PUB",
        gap_id: "GAP-PFS-TRIAL",
        tactic_id: "TAC-PUB-PFS",
        overall: "not_relevant",
        rationale: "Dissemination of already-generated evidence. Does not add coverage.",
        who: hale,
        values: {
          relevance: "partial",
          population: "yes",
          intervention: "yes",
          comparator: "yes",
          outcomes: "yes",
          geography: "yes",
          setting: "unknown",
          timing: "partial",
          methodology: "unknown",
          decision_utility: "partial",
        },
      }),
    ],
    mapping_suggestions: [],
    residual_gap_suggestions: [],
    residuals: [
      {
        id: "RES-ELDERLY-SOC",
        gap_id: "GAP-ELDERLY-CE",
        statement:
          "Comparative outcomes versus relevant regional standard of care in elderly patients",
        domain: "comparative_effectiveness",
        draft_rationale:
          "Parent GAP-ELDERLY-CE preserved. Chart review covers population/treatment/outcomes; comparator and decision utility are No. Draft locked by HEOR.",
        lock: lock(...rao, "Residual of elderly CE gap."),
      },
      {
        id: "RES-RECUR-COST",
        gap_id: "GAP-RECUR-ECON",
        statement:
          "Direct economic costs of recurrence, including repeat procedures and subsequent treatment",
        domain: "economics",
        draft_rationale:
          "Parent GAP-RECUR-ECON preserved. Natural-history + HCRU address clinical burden and hospitalisations; costs remain.",
        lock: lock(...rao, "Residual of recurrence economics."),
      },
      {
        id: "RES-CNS",
        gap_id: "GAP-CNS",
        statement:
          "Intracranial ORR and duration in patients with brain metastases",
        domain: "efficacy",
        draft_rationale: "No adequate tactic. Parent gap preserved.",
        lock: lock(...hale, "Open CNS residual."),
      },
      {
        id: "RES-PERSIST",
        gap_id: "GAP-PERSIST",
        statement:
          "Six-month discontinuation in US routine care for Aetna/UHC P&T",
        domain: "adherence",
        draft_rationale: "Planned claims study does not yet exist as evidence.",
        lock: lock(...okonkwo),
      },
      {
        id: "RES-IRA",
        gap_id: "GAP-IRA",
        statement:
          "IRA negotiated-price budget-impact scenario",
        domain: "budget_impact",
        draft_rationale: "A tactic existing at WAC does not address the IRA question.",
        lock: lock(...okonkwo),
      },
      {
        id: "RES-CAREGIVER",
        gap_id: "GAP-CAREGIVER",
        statement:
          "Caregiver burden and frail-patient PRO",
        domain: "caregiver_burden",
        draft_rationale: "Registry PROs do not include caregiver instruments.",
        lock: lock(...hale),
      },
      {
        id: "RES-HCRU-ED",
        gap_id: "GAP-HCRU",
        statement:
          "Emergency-department use and outpatient burden after recurrence",
        domain: "hcru",
        draft_rationale: "Hospitalisations better covered than ED/OP.",
        lock: lock(...rao),
      },
      {
        id: "RES-SEQ",
        gap_id: "GAP-SEQ",
        statement:
          "Velmara versus NX-441 after osimertinib failure",
        domain: "treatment_sequencing",
        draft_rationale: "Registry captures patterns; NX-441 comparator is thin. Parent gap preserved.",
        lock: lock(...chen),
      },
      {
        id: "RES-QOL",
        gap_id: "GAP-QOL",
        statement:
          "Frail-patient PRO and routine-care QoL beyond mixed-age trial EORTC",
        domain: "qol_pro",
        draft_rationale: "Registry PROs exist; frail instruments do not. Parent gap preserved.",
        lock: lock(...hale),
      },
      {
        id: "RES-OS",
        gap_id: "GAP-OS",
        statement:
          "Overall survival beyond the VEL-301 primary PFS analysis for the 2026 value story",
        domain: "long_term_outcomes",
        draft_rationale: "LTFU is the right tactic at the wrong time. Residual drafted; priority not yet locked.",
        lock: unlocked(),
      },
      {
        id: "RES-ILD",
        gap_id: "GAP-ILD",
        statement:
          "ILD and QT incidence in routine care",
        domain: "safety",
        draft_rationale: "Drafted from the candidate ILD/QT gap. Parent preserved. Human must accept or reject.",
        lock: unlocked(),
      },
    ],
    priorities: [
      {
        id: "PRI-ELDERLY",
        residual_id: "RES-ELDERLY-SOC",
        suggested_score: 86,
        suggested_band: "critical",
        band: "critical",
        override_reason: null,
        reasons: [
          "Strategic importance 5/5",
          "HTA elderly package 15 Jan 2027",
          "Comparator uncovered",
          "Stakeholder HTA/HEOR",
        ],
        lock: lock(...lead, "Accepted suggested critical band."),
      },
      {
        id: "PRI-IRA",
        residual_id: "RES-IRA",
        suggested_score: 78,
        suggested_band: "critical",
        band: "critical",
        override_reason: null,
        reasons: ["US P&T + IRA", "WAC BIM is not coverage"],
        lock: lock(...lead),
      },
      {
        id: "PRI-PERSIST",
        residual_id: "RES-PERSIST",
        suggested_score: 74,
        suggested_band: "high",
        band: "high",
        override_reason: null,
        reasons: ["Aetna/UHC Dec 2026"],
        lock: lock(...lead),
      },
      {
        id: "PRI-RECUR",
        residual_id: "RES-RECUR-COST",
        suggested_score: 68,
        suggested_band: "high",
        band: "high",
        override_reason: null,
        reasons: ["CEA input freeze Nov 2026"],
        lock: lock(...lead),
      },
      {
        id: "PRI-CNS",
        residual_id: "RES-CNS",
        suggested_score: 61,
        suggested_band: "high",
        band: "medium",
        override_reason:
          "Medical importance high but HTA package can ship without dedicated CNS DOR if registry progression is cited. Overrode to medium.",
        reasons: ["KOL demand vs decision date"],
        lock: lock(...lead, "Overrode high → medium."),
      },
      {
        id: "PRI-HCRU",
        residual_id: "RES-HCRU-ED",
        suggested_score: 52,
        suggested_band: "medium",
        band: "medium",
        override_reason: null,
        reasons: ["Partial hospitalisations already in hand"],
        lock: lock(...lead),
      },
      {
        id: "PRI-SEQ",
        residual_id: "RES-SEQ",
        suggested_score: 0,
        suggested_band: "high",
        band: "high",
        override_reason: null,
        reasons: ["Human-locked. The engine does not assign priority."],
        lock: lock(...lead),
      },
      {
        id: "PRI-QOL",
        residual_id: "RES-QOL",
        suggested_score: 0,
        suggested_band: "medium",
        band: "medium",
        override_reason: null,
        reasons: ["Human-locked. The engine does not assign priority."],
        lock: lock(...lead),
      },
      {
        id: "PRI-CARE",
        residual_id: "RES-CAREGIVER",
        suggested_score: 44,
        suggested_band: "medium",
        band: "low",
        override_reason: "Patient-centred story, not HTA-critical this cycle.",
        reasons: ["Patient-centred story, not HTA-critical this cycle"],
        lock: lock(...lead),
      },
    ],
    roadmap: [
      {
        id: "RM-REG",
        tactic_id: "TAC-REG",
        residual_ids: ["RES-HCRU-ED"],
        start_date: "2026-04-01",
        evidence_available: "2027-09-01",
        owner: "L. Chen",
        note: "Ongoing registry — synergy across sequencing, OS, HCRU, PRO. Does not close elderly SoC.",
        lock: lock(...lead),
      },
      {
        id: "RM-BIM",
        tactic_id: "TAC-BIM",
        residual_ids: ["RES-IRA"],
        start_date: "2026-10-01",
        evidence_available: "2026-12-15",
        owner: "T. Okonkwo",
        note: "Planned IRA scenario. WAC BIM stays off the roadmap (completed programme inventory).",
        lock: lock(...lead),
      },
      {
        id: "RM-CLAIMS",
        tactic_id: "TAC-CLAIMS",
        residual_ids: ["RES-PERSIST"],
        start_date: "2026-11-01",
        evidence_available: "2027-04-01",
        owner: "L. Chen",
        note: "Planned persistence study for Aetna/UHC.",
        lock: lock(...lead),
      },
      {
        id: "RM-LTFU",
        tactic_id: "TAC-LTFU",
        residual_ids: [],
        start_date: "2027-01-01",
        evidence_available: "2028-06-01",
        owner: "ClinDev",
        note: "Planned OS follow-up. Timing misses 2026 value story.",
        lock: lock(...lead),
      },
      {
        id: "RM-PUB",
        tactic_id: "TAC-PUB-PFS",
        residual_ids: [],
        start_date: "2026-11-15",
        evidence_available: "2027-03-01",
        owner: "SciComms",
        note: "Dissemination tactic for the addressed PFS gap.",
        lock: lock(...hale),
      },
    ],
    audit: [
      {
        id: "AUD-001",
        at: AT,
        actor_name: "S. Iyer",
        actor_function: "evidence_lead",
        entity_type: "plan",
        entity_id: "ASSET-VELMARA",
        action: "seed",
        detail: "Loaded Velmara IEGP seed. Living plan, no annual snapshot.",
      },
    ],
    gold_needs: [
      { id: "GOLD-N-001", statement: "Need to understand the economic burden associated with recurrence after velmaratinib.", source_id: "SRC-INT-HEOR", must_find: true },
      { id: "GOLD-N-002", statement: "Limited evidence characterises direct costs of repeat procedures in routine practice.", source_id: "SRC-INT-HEOR", must_find: true },
      { id: "GOLD-N-003", statement: "Need comparative effectiveness of Velmara versus regional standard of care in elderly patients.", source_id: "SRC-INT-HEOR", must_find: true },
      { id: "GOLD-N-004", statement: "We don't have enough evidence in patients aged 65 and over.", source_id: "SRC-INT-HEOR", must_find: true },
      { id: "GOLD-N-005", statement: "KOLs need to know intracranial outcomes.", source_id: "SRC-INT-MED", must_find: true },
      { id: "GOLD-N-006", statement: "Limited evidence on CNS response and duration in patients with brain metastases remains an open question.", source_id: "SRC-INT-MED", must_find: true },
      { id: "GOLD-N-007", statement: "Need to characterise real-world treatment sequencing after osimertinib failure.", source_id: "SRC-INT-MED", must_find: true },
      { id: "GOLD-N-008", statement: "Aetna and UnitedHealthcare need to understand 6-month discontinuation in routine care.", source_id: "SRC-INT-ACCESS", must_find: true },
      { id: "GOLD-N-009", statement: "Need to quantify IRA net-price exposure for Velmara.", source_id: "SRC-INT-ACCESS", must_find: true },
      { id: "GOLD-N-010", statement: "Limited evidence remains on emergency-department use and outpatient burden.", source_id: "SRC-TLR-001", must_find: true },
      { id: "GOLD-N-011", statement: "Evidence gap on comparative effectiveness in the elderly is not closed.", source_id: "SRC-TLR-001", must_find: true },
      { id: "GOLD-N-012", statement: "Insufficient evidence on caregiver burden and on PRO in frail patients.", source_id: "SRC-TLR-001", must_find: true },
      { id: "GOLD-N-013", statement: "We need to understand budget impact under IRA.", source_id: "SRC-HEOR-001", must_find: true },
      { id: "GOLD-N-014", statement: "Limited evidence on HCRU associated with recurrence feeds the model.", source_id: "SRC-HEOR-001", must_find: true },
    ],
    gold_coverages: [
      { id: "GOLD-C-001", gap_id: "GAP-ELDERLY-CE", tactic_id: "TAC-ELDERLY-RWE", overall: "partial" },
      { id: "GOLD-C-002", gap_id: "GAP-ELDERLY-CE", tactic_id: "TAC-VEL-301", overall: "limited" },
      { id: "GOLD-C-003", gap_id: "GAP-PFS-TRIAL", tactic_id: "TAC-VEL-301", overall: "full" },
      { id: "GOLD-C-004", gap_id: "GAP-PFS-TRIAL", tactic_id: "TAC-PUB-PFS", overall: "not_relevant" },
      { id: "GOLD-C-005", gap_id: "GAP-RECUR-ECON", tactic_id: "TAC-NH", overall: "partial" },
      { id: "GOLD-C-006", gap_id: "GAP-SEQ", tactic_id: "TAC-REG", overall: "partial" },
    ],
    gap_versions: [],
  };

  return {
    ...state,
    residual_gap_suggestions: [],
    gaps: state.gaps.map((gap) => ({
      ...gap,
      parent_gap_id: null,
      computed_status:
        gap.status === "validated_open" ||
        gap.status === "validated_partial" ||
        gap.status === "validated_addressed"
          ? gap.status
          : null,
      status_override: null,
      retired: false,
      human_validated: gap.status !== "candidate" && gap.status !== "excluded",
    })),
    residuals: state.residuals.map((residual) => ({
      ...residual,
      review_status: residual.lock.locked ? ("accepted" as const) : ("candidate" as const),
      created_gap_id: null,
    })),
  } as IegpState;
}

function need(
  id: string,
  n: {
    statement: string;
    domain: import("./enums").EvidenceDomain;
    stakeholder: ActorFunction;
    objective_id: string;
    decision_supported: string;
    geography: string;
    population: string;
    intervention: string;
    comparator: string;
    outcome: string;
    timing: string;
    source_id: string;
    source_quote: string;
    status: "candidate" | "accepted" | "rejected";
    who: [string, ActorFunction] | null;
  },
) {
  const { who, ...rest } = n;
  return {
    id,
    ...rest,
    confidence: n.status === "candidate" ? 0.55 : 0.86,
    status_lock: who ? lock(...who) : unlocked(),
  };
}

function tactic(
  id: string,
  t: {
    name: string;
    type: import("./enums").TacticType;
    description: string;
    evidence_question: string;
    population: string;
    intervention: string;
    comparator: string;
    outcomes: string;
    geography: string;
    data_source: string;
    study_design: string;
    lifecycle_stage: string;
    status: import("./enums").TacticStatus;
    start_date: string | null;
    evidence_available: string | null;
    owner: string;
    function: ActorFunction;
    budget: string | null;
    intended_use: string;
    who: [string, ActorFunction] | null;
  },
) {
  const { who, ...rest } = t;
  return {
    id,
    ...rest,
    review_status: "accepted" as const,
    lock: who ? lock(...who) : unlocked(),
  };
}
